### ISSUE TITLE
Gutter "dot" adds large whitespace

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/linter-ui-default#112]
The [current](https://github.com/steelbrain/linter-ui-default/tree/11e187d4f86230ca6d5ec339517bce468a02c6cc) gutter implementation seems to _not_ remove the extra space in the line number section fro mthe old method, and adds at least that much into the code area.

Here is the Seti theme, which shows the differentiation between the line area (black) and code (dark grey):
![image](https://cloud.githubusercontent.com/assets/427137/16970471/26d566c8-4dd1-11e6-9b4f-15362ea09989.png)
Note that this theme shows excess space between the "dot" and the code compared to the other two themes.

One Dark makes no color distinction between the line number section and the code, but seems to have at least the same amount of total wasted space as Seti:
![image](https://cloud.githubusercontent.com/assets/427137/16970528/93804964-4dd1-11e6-901e-ac0c51b8ccb1.png)

While Atom Dark only seems to have the excess space in the line number section:
![image](https://cloud.githubusercontent.com/assets/427137/16970494/4dfb910a-4dd1-11e6-9da3-c5c0cd4e017d.png)

---

If the gutter position is changed to `Left`, the following is the result:

Seti:
![image](https://cloud.githubusercontent.com/assets/427137/16970592/f6799160-4dd1-11e6-93f0-075d70ac1a33.png)

One Dark:
![image](https://cloud.githubusercontent.com/assets/427137/16970570/d8635972-4dd1-11e6-8e2b-75f133645fc9.png)

Atom Dark:
![image](https://cloud.githubusercontent.com/assets/427137/16970618/207fced4-4dd2-11e6-903e-cbcf2d0b5b94.png)

**Comment by KaneezIqbal** [comment]
Some investigation led me to believe that the extra space is entirely psychological. There's extra space on the left but that's only from the dropdown of text editor wraps. If we move the gutter highlights the left, "their" space area no longer include wraps and their dropdown space so seems shrunk. I used css measurements to confirm.

**Comment by steelbrain** [comment]
Agreed, closing based on above comment
