### ISSUE TITLE
Setting for sort order of errors and warnings?

### ISSUE THREAD

**Issue by beowulfof** [steelbrain/linter-ui-default#115]
As requested, I reopen this here again.

How about a setting to switch ordering of linter results? As of by now, warning will always be shown first, before errors, I'd really appreciate a setting to switch that, as, at least for me, warnings are not in the focus like errors.

**Comment by steelbrain** [comment]
Thank you for your request, the latest linter UI will have three severities, error, warning and info (priority more -> less). The highest priority messages will be shown above others and will be the dominating colors for the gutter and are the dominating colors for tree view.

**Comment by steelbrain** [comment]
This has been implemented in master with the new panel. You can now sort by severity, line and file or all at once

**Comment by Arcanemagus** [comment]
Just to link it together, this was fixed in #127.
