### ISSUE TITLE
React error

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/linter-ui-default#138]
Noticed this while launching Atom in dev mode, if I can find steps to reproduce I'll update.

![image](https://cloud.githubusercontent.com/assets/427137/19200687/307f247e-8c7f-11e6-9bfd-0168e3487d2e.png)

**Comment by Arcanemagus** [comment]
As an update, I'm pretty sure I saw this pop up when hovering over code (making the tooltip show).

**Comment by steelbrain** [comment]
Fixed as of https://github.com/steelbrain/linter-ui-default/commit/fce3ca63de78b332cca240a78744d7f3ef6e261f
