### ISSUE TITLE
Lines are listed 0-indexed instead of 1-indexed

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/linter-ui-default#140]
The "Line" column in the table is showing 0-indexed numbers instead of the 1-indexed visible in the editor.

![image](https://cloud.githubusercontent.com/assets/427137/19401710/afc1f314-9211-11e6-92a9-2afb79368464.png)

**Comment by Arcanemagus** [comment]
Looks like this is a problem again, possibly due to #147?

**Comment by Arcanemagus** [comment]
Actually this was broken in https://github.com/steelbrain/linter-ui-default/commit/34b0755111bac1a5114dfeaef9ed950c222f7f0a.

**Comment by steelbrain** [comment]
Fixed in https://github.com/steelbrain/linter-ui-default/commit/c67fb73

**Comment by Arcanemagus** [comment]
Confirming as fixed in c67fb73.
