### ISSUE TITLE
Error Counter

### ISSUE THREAD

**Issue by JLCCI** [steelbrain/linter-ui-default#173]
First of all, thank you for all your work with the linter!

I have a small comment around the new error counter - specifically, it looks quite out of place with some themes and it's not always useful to have it separated into three values. 

![screenshot from 2017-03-14 11-19-42](https://cloud.githubusercontent.com/assets/18163728/23883198/cd72f4cc-08a8-11e7-8709-8d138bbd84cf.png)

Would it perhaps be possible to add an option to:
1) Revert back to previous state when the errors were shown in one message in white or red?
2) Alternatively, an option to remove the boxes and match the colour of other text in the panel (brighter)?

Small tweaks but hopefully something you could consider. Thanks in advance for any implementations.

**Comment by steelbrain** [comment]
Hi @JLCCI, we could certainly fix the color variables used inside the error counter, Thanks for the report!

**Comment by JLCCI** [comment]
Fantastic, many thanks. Having an option to remove the boxes around the number would also be great to keep everything clean (or let the user control the color if removing is not an option).

**Comment by steelbrain** [comment]
Hi @JLCCI 

I've done some digging deep and found that we are relying on the theme to provide us with correct colors for the highlights, I've confirmed that this works fine in the default ones so I recommend you open an issue in the themes you're having trouble in and tell the authors to normalize the font colors for the `.highlight` classes!

Thanks again for opening this issue

**Comment by JLCCI** [comment]
I see, thanks for pointing it out! Still, if possible, it would be fantastic if you could bring back the old style of reporting errors (just a text in red), it was a really clean solution that I think many people liked.

Keep up the good work with the linter.

**Comment by steelbrain** [comment]
Glad you liked it @JLCCI but we had tons of people disliking it :D
People wanted to know exact counts of how many errors/warnings there were, that's how we ended up on the current one

**Comment by JLCCI** [comment]
Sure, I appreciate that. :) That is why I mentioned this as an 'option' that people can change in the settings since you already have the code for that (while keeping the three counters as default).

Anyway it is not a huge deal, would be nice to have it if you have time though! All the best. :)
