### ISSUE TITLE
Option to position and/or hide counters

### ISSUE THREAD

**Issue by cbrnr** [steelbrain/linter-ui-default#175]
Currently the position at the left of the status bar (right next to the row/column indicator) is pretty noisy, because it changes all the time depending on what's shown to the left of it. It would be nice to have an option to place the counter UI at the right side of the status bar.

In addition, the UI should only show for file types where linters are installed. Currently, it shows up for all files, even for new unsaved ones (at least it is hidden for the settings page). I don't know if there's a way to access the panel without the counter UI, but if so, an option to completely hide the counter would also be useful.

**Comment by steelbrain** [comment]
While we cannot hide the UI for files that have no linter installed (we have already considered it and decided against it because ideally you should have a linter provider for every file type and hiding/showing clutter is not worth it). I'll definitely try to add an option to show it on the left
