### ISSUE TITLE
Extra border in the bottom panel when having no error

### ISSUE THREAD

**Issue by HiDeoo** [steelbrain/linter-ui-default#176]
When the linter do not have any error to report, the bottom panel still show an extra "border" of 1px.

__Expected outcome:__ Have nothing extra visible when no error or no panel are visible.

Toggling quickly the `Show Panel` option display this behavior even in the Settings pane as shown in the following gif (the same issue also happens in any file):

![linter](https://cloud.githubusercontent.com/assets/494699/23891702/e164b1a2-0897-11e7-9076-fb43f88495be.gif)

I don't think it's related to the UI theme as I used One Light in the previous gif as the issue is more visible in this theme but the same thing happens with One Dark.

*Atom version: 1.15.0*
*Linter version: 2.0.0*
*Linter-ui-default version: 1.0.0*

**Comment by steelbrain** [comment]
Hi @HiDeoo 

Do you have the `Always Take Minimum Space` config enabled?

**Comment by HiDeoo** [comment]
If you're talking about the `Panel Takes Minimum Height` option, it's enabled at the moment, I think this is the default configuration? I don't remember changing it.

For information, disabling this option did not change the behavior / issue.

**Comment by steelbrain** [comment]
Will investigate, thanks for the report

**Comment by HiDeoo** [comment]
I'm adding a gif where all my options are visible if that can help. The only thing I remember changing is the `Decorate On Tree View` option (reverting it don't change anything related to the issue).

![linter2](https://cloud.githubusercontent.com/assets/494699/23892290/3b86e324-089a-11e7-9144-367c43c6973d.gif)

**Comment by steelbrain** [comment]
Confirmed, fixing

**Comment by steelbrain** [comment]
A fix is up in https://github.com/steelbrain/linter-ui-default/pull/177

Can you please confirm that it works for you?

**Comment by HiDeoo** [comment]
Just checked using this branch, it now works as expected 👍

**Comment by steelbrain** [comment]
The change has been merged in and will be a part of the next linter release
