### ISSUE TITLE
Blank space to the right of the gutter

### ISSUE THREAD

**Issue by 50Wliu** [steelbrain/linter-ui-default#189]
![blank-space](https://cloud.githubusercontent.com/assets/2766036/23929557/7b97303c-08fd-11e7-8a18-a847eef9ea50.png)
I understand that the blank space between the cursor and the gutter is supposed to contain the linter decorations, however it is extremely visually distracting because it appears to be a part of the editor when in fact it is a part of the gutter.

I am using the Fizzy syntax theme, which appears to be controlling the background color using a selector of `atom-text-editor.editor .gutter`.

I am using linter-ui-default@1.1.0.

**Comment by steelbrain** [comment]
Will investigate, Thank You

**Comment by steelbrain** [comment]
<img align="left" src="https://cloud.githubusercontent.com/assets/4278113/23930873/e2a3a8f2-0950-11e7-8164-06c98456bc8f.png">
<img src="https://cloud.githubusercontent.com/assets/4278113/23930875/e2d51ed2-0950-11e7-997d-a3cac6b3d0d6.png">

<div align="left">
We currently do the one on the left, we can do the one on the right but it won't look good either. I think this is the price of having a gutter, sadly. One thing that would main it less painful is the colors from your theme.
</div>

**Comment by 50Wliu** [comment]
I would much prefer the one on the right (isn't this what it used to look like in linter v1?) so that it's clearly a part of the gutter.

**Comment by steelbrain** [comment]
I can revert it back, but for the reference, it was made transparent because of https://github.com/steelbrain/linter/issues/1151

**Comment by steelbrain** [comment]
I've opened https://github.com/steelbrain/linter-ui-default/pull/190 
Can you please confirm that it fixes this issue?

**Comment by 50Wliu** [comment]
I can check tomorrow.  If I don't get back to you by the 17th, please ping me on the PR.

**Comment by dsandstrom** [comment]
Unfortunately, the current css doesn't solve either.  I still have the gap when I disable my custom styles.  However, my suggested improvement in linter#1151 is not a good solution because it covers up the collapse carets.

Is it possible to carry over the `current-line` class to linter gutter?  This way we can style it correctly.

**Comment by steelbrain** [comment]
Actually, it is possible to carry over the `current-line` class, though we'll have to add custom logic that observers editor movement instead of setting a parameter in atom-core (maybe Atom should do this because other gutter containers would need this too?) but I'll try to get an experiment up soon

**Comment by steelbrain** [comment]
Carrying over the styles from the line number gutter worked nicely, I'll try to open an issue in Atom asking for this to be done on all gutter containers by default but until then

![kap new](https://cloud.githubusercontent.com/assets/4278113/23975302/a1ea4468-0a01-11e7-8e11-b2dc7a333951.gif)

**Comment by dsandstrom** [comment]
Thanks @steelbrain. Awesome work on linter/linter-ui-default.

Are you using linter-ui-default or a custom ui?

**Comment by steelbrain** [comment]
It's the default UI (linter-ui-default), but unpublished changes. These changes will be included in the next version
