### ISSUE TITLE
Linter Message when keyboard cursor is on current line

### ISSUE THREAD

**Issue by hnguyen94** [steelbrain/linter-ui-default#192]
Hey,

before that version, when I go the linter warning line with the keyboard I got a linter box
After the update I've to hover the line with my mouse. Is it possible to add that feature again? :)
I use the mouse rarely..

**Comment by steelbrain** [comment]
Change your `Tooltip Follows` configuration to `Keyboard` :)

**Comment by hnguyen94** [comment]
Daaamn, sorry for creating that Issue! 
Keep it working! Nice plugin
