### ISSUE TITLE
Tooltip background is too bright

### ISSUE THREAD

**Issue by VladShcherbin** [steelbrain/linter-ui-default#198]
They are too bright to use with dark color scheme.

<img width="901" alt="screen shot 2017-03-15 at 10 59 12 pm" src="https://cloud.githubusercontent.com/assets/6711845/23968325/53464fce-09d3-11e7-861c-8f375b4d6101.png">

Is it somehow possible to make them dark, like it was in previous version?

**Comment by VladShcherbin** [comment]
Same with warnings, looks really bad to me.

<img width="641" alt="screen shot 2017-03-15 at 11 03 27 pm" src="https://cloud.githubusercontent.com/assets/6711845/23968420/acb3a7aa-09d3-11e7-9905-465860a68243.png">

**Comment by steelbrain** [comment]
Hi @VladShcherbin The second screenshot you provided is a provider issue, provider is using html and is not painting it's classes properly. The first one is legit.

The background color red-ish tells that it's an error, we could make it lighter, or darker, can you send send us some color code that you think will be more appropriate?

**Comment by VladShcherbin** [comment]
@steelbrain I'm not sure if the background color would help, it will still stand out a lot.

As for me, I prefer a small label with bg-color and a normal tooltip. Something like this one, with dark or light background & an error label:

![image](https://i.github-camo.com/e8df74f380dee6729adf822086dda174f2a76c1f/68747470733a2f2f6769746875622e636f6d2f73696e647265736f726875732f61746f6d2d6c696e7465722d786f2f7261772f6d61737465722f73637265656e73686f742e706e67)

**Comment by IgorKonovalov** [comment]
Yes, small label was much much better. Also the font size is nearly twice bigger than before - it takes too much space. The bottom panel is awesome.

**Comment by IgorKonovalov** [comment]
Here is an example of tooltip taking too much space: 
![app js d__igor_git_little_projects_hackernews atom 2017-03-18 19 57 19](https://cloud.githubusercontent.com/assets/8154172/24074225/7e696b20-0c15-11e7-8fac-2627713b7404.png)

**Comment by steelbrain** [comment]
Hi @IgorKonovalov 

That last one is actually a bug in linter-eslint, and it was fixed IIRC (cc @Arcanemagus)

**Comment by Arcanemagus** [comment]
Actually the "bug" was that it _wasn't_ working that way before. I'm not sure if it's the latest ESLint but what you see there is what ESLint is giving back to `linter-eslint`.

**Comment by steelbrain** [comment]
Correct me if I'm wrong but anything after the error message seems to be the error context and is not necessary and shouldn't be shown inside Atom regardless of where it's coming from. If it's coming from ESLint linter-eslint should handle the behavior and make it Atom friendly
