### ISSUE TITLE
Function.extractParams is deprecated.

### ISSUE THREAD

**Issue by widyaop** [steelbrain/linter-ui-default#203]
Assigning custom properties to a marker when creating/copying it is
deprecated. Please, consider storing the custom properties you need in
some other object in your package, keyed by the marker's id property.
```
Function.extractParams (C:\Users\Pande\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\text-buffer\lib\marker.js:43:14)
MarkerLayer.markRange (C:\Users\Pande\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:215:71)
DisplayMarkerLayer.markBufferRange (C:\Users\Pande\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\text-buffer\lib\display-marker-layer.js:105:52)
TextEditor.markBufferRange (C:\Users\Pande\AppData\Local\atom\app-1.15.0\resources\app.asar\src\text-editor.js:1776:38)
handlePositionChange (C:\Users\Pande\.atom\packages\linter-ui-default\lib\editor\index.js:115:38)
<unknown> (C:\Users\Pande\.atom\packages\linter-ui-default\lib\editor\index.js:143:9)
```

**Comment by steelbrain** [comment]
It's most likely coming from another package, can you please post a list of community installed packages?

**Comment by silveryiris** [comment]
Have the same issue here.

My installed community packages are :

- Stylus
- atom-beautify
- language-pug
- language-vue
- linter-eslint
- pigments
- qcolor

Installed packages provided by @steelbrain are : 

- busy-signal
- intentions
- linter
- linter-ui-default

**Comment by SpeedrunnerG55** [comment]
i am having the same issue. my list of packages are: 
atomic-clock
auto-indent
busy-signal
envy-theme
file-icons
gpp-compiler
intentions
lint
linter
linter-gcc
linter-ui-default
linter-write-good
merge-conflicts
minimap
minimap-bookmarks
minimap-curserline
minimap-find-and-replace
minimap-highlight-selected
minnimap-selection
minimap-split-diff
platformio-ide-terminal
split-diff

**Comment by MoronVV** [comment]
Same here:
**Function.extractParams - /usr/lib/atom/node_modules/text-buffer/lib/marker.js:43:14
MarkerLayer.markRange - /usr/lib/atom/node_modules/text-buffer/lib/marker-layer.js:215:71
DisplayMarkerLayer.markBufferRange - /usr/lib/atom/node_modules/text-buffer/lib/display-marker-layer.js:105:52
TextEditor.markBufferRange - /usr/lib/atom/src/text-editor.js:1776:38
handlePositionChange - /home/moronvv/.atom/packages/linter-ui-default/lib/editor/index.js:115:38
<unknown> - /home/moronvv/.atom/packages/linter-ui-default/lib/editor/index.js:143:9**

**Comment by steelbrain** [comment]
Are you guys getting this after the latest update `1.2.0` or on `1.1.0`?

**Comment by SpeedrunnerG55** [comment]
1.2.0

**Comment by steelbrain** [comment]
Were you getting this before the update?

**Comment by SpeedrunnerG55** [comment]
no

**Comment by suryaavala** [comment]
I installed 1.1.0 couple of hours ago, everything seemed to be fine. 
Then got the update for 1.2.0, started getting this Warning.

**Comment by steelbrain** [comment]
I've pinpointed the error source, expect a hotfix soon

**Comment by steelbrain** [comment]
v1.2.1 is out people, tl;dr: Atom docs were out of date, I specified a parameter that no longer exists
