### ISSUE TITLE
Tooltip Follows: Both

### ISSUE THREAD

**Issue by OmeGak** [steelbrain/linter-ui-default#206]
I wonder why `Both` is not an option in `Tooltip Follows`. I generally move around with the keyboard and I want to see the errors/warnings on the line I'm currently editing, but oftentimes I also want to check the errors on other lines without having to move the cursor. I would expect hovering with the mouse would also display them, but the option is not there.

**Comment by steelbrain** [comment]
Oh God 😅 

Both gets unpredictable and complicated fast, what if you move both of your mouse and keyboard?

**Comment by OmeGak** [comment]
Doesn't sound too complicated if you are fine with showing a maximum of two tooltips at the same time.

If the keyboard cursor is sitting on top of an underlined error I would get the tooltip there. Additionally, if I'm hovering an underlined error, i would get a second tooltip there. If the mouse hovers the same error my keyboard cursor is displaying nothing extra tooltip is displayed.

**Comment by Arcanemagus** [comment]
I'm _definitely_ 👎 for multiple tooltips active at once. I can agree to a "Both" option that follows whatever updated last though.

**Comment by Positive07** [comment]
Here is an idea of how a "Both" mode could be implemented:
* Track when the mouse is moved (as you are probably doing in the "Tooltip Follows: Mouse") and save the tooltip if any, its position, and the update time
* Track keyboard movement (as you probably do in the "Tooltip Follows: Keyboard") and save the tooltip if any, its position, and the update time
* Then you check:
  * If neither of them has a tooltip you display nothing
  * If only one of them has a tooltip you display that tooltip
  * If both have a tooltip you only display the one with the greater update time

**Comment by Positive07** [comment]
I can code the behaviour described above if wanted and submit a pull-request if that is desired. Is there any interest in this way of handling it?

**Comment by steelbrain** [comment]
I would appreciate a PR solving this

Tho it has to match the criteria @Arcanemagus described above :)

**Comment by Positive07** [comment]
Does the description of the behaviour I described, match what @Arcanemagus wants? There would never be two tooltips in the screen at once.

**Comment by Arcanemagus** [comment]
I _think_ it does? It doesn't sound like how the tooltips actually work from what I know, but it's a decent pseudo-code for it.

**Comment by Positive07** [comment]
Yeah I'll check how they work and try to handle it

**Comment by steelbrain** [comment]
Thought about it again, sounds like a decent request

Added in https://github.com/steelbrain/linter-ui-default/pull/304
