### ISSUE TITLE
Add Option to use another search engine 

### ISSUE THREAD

**Issue by Joinyy** [steelbrain/linter-ui-default#213]
By clicking on the Link symbol in the tooltip we get redirectet to a google search. I would love to see other search engines like duckduckgo also supported or just a string input window for urls like `https://duckduckgo.com/?q=` for even more customizing support.

**Comment by steelbrain** [comment]
Hi @Joinyy 

I've talked to @Arcanemagus about this and we're going to remove the jump to search entirely. We have a `url` property for providers in API v2 so they can provide users with a jump to url, but when they don't provide a url, instead of filling it with google search we'll be hiding it

What do you think about this change?

**Comment by Joinyy** [comment]
Hi @steelbrain ,

it's okay, but I personally wouldn't like to do the setting for all providers. I use 2 Providers for my C++ Projects (clang and cpp linter) and if I had to set my search URL in both, that wouldn't be a good user experience I think (plus more linter-providers for other projects in other languages).

Also it is on the UI so in my opinion these kind of settings could be done in the UI package entirely for all providers.

**Comment by Arcanemagus** [comment]
@Joinyy What @steelbrain means is the "auto search URL" is planned to be removed _entirely_. If providers give a URL it will be used, otherwise you would need to copy the text and paste it into a search engine of your choice on your own.

**Comment by Joinyy** [comment]
I understood and think you did some arguing about that so I am going to close this Issue after your last answers 👌 

Why I was arguing against it is that the feature isn't completely removed if some providers can "activate" it by giving a URL. If some providers like the feature and put in some URLs I would put in duckduckgo in all of them. I can't think of a usecase where you want to search for java problems via Bing, for C++ errors via Google and for python with Yahoo 😄  I think many users would immediatly search this addon for help if they didn't know why C++ projects have this nice feature and others don't (for example).

I hope you can understand what I mean 👍

**Comment by Arcanemagus** [comment]
Ah, the search provided there was just a fallback. The providers that give URLs have a far better understanding of what is going on and can provide much better links. For example `linter-eslint` links people _directly_ to the rule that triggered the message (eg: [no-extra-semi](http://eslint.org/docs/rules/no-extra-semi)).

**Comment by Joinyy** [comment]
Ok that makes sense. Ty for your answers.
