### ISSUE TITLE
Use Theme Background Color for .linter-status-count

### ISSUE THREAD

**Issue by pingshunhuangalex** [steelbrain/linter-ui-default#216]
Hi @steelbrain 

I'm using the latest `Atom 1.16.0-beta0` with `material ui theme`. With the recent magnificent linter 2.1.0 update, I noticed that the `.linter-status-count` area doesn't look quite right...

![image](https://cloud.githubusercontent.com/assets/17170199/24069696/02d5be0e-0c02-11e7-8d58-8941aadd4e9c.png)

I'm not sure if the backgrond color there is intentional, but I think using the theme background color or a slightly darker background color (a semi-transparent color filter) would make it look more natural, considering it's not really specified in the [style](https://github.com/steelbrain/linter-ui-default/blob/master/styles/linter-ui.less#L121). Thanks.

**Comment by steelbrain** [comment]
Hi @pingshunhuangalex 

You are correct, we do not specify the colors in the styles, we use the Atom theme classes to style the bottom status, please reopen this on the material ui theme repo asking for better color variables

**Comment by pingshunhuangalex** [comment]
Thanks @steelbrain for the clarification.

And someone has already beaten me to it regarding this [issue](https://github.com/atom-material/atom-material-ui/issues/369).

I'm sure it'll all be resolved in the coming `material-ui-theme` 2.0. Thanks for keeping Atom thriving and prosperous. Great work on `Linter 2.0`
