### ISSUE TITLE
Tooltip follows: mouse on cursor-move + keyboard on jump-to-lint

### ISSUE THREAD

**Issue by colin-kiegel** [steelbrain/linter-ui-default#218]
It is possible to **jump** the cursor to a lint via shortcuts or the lint panel.
The lint tooltip currently follows _either_ the mouse or the cursor.

Both have their own problems (IMO):
- **follow mouse**: explicitly jumping to a lint does _not_ show the lint, despite the fact that jumping to a lint demonstrates interest in it.
- **follow keyboard**: tends to obstruct the view while typing.

I would really like a mode which shows lints if (and only if) you expressed interest in them. Either by hovering your mouse or jumping to the lint. I think the best of both current modes can be achieved by intelligently switching between two states.

# Proposal

Add a new option _Tooltip follows: mouse on cursor-move + keyboard on jump-to-lint_ (pending bikeshedding on naming).

With this new option I would imagine linter to have two states `moving` and `jump`, as follows. The default state would be `moving`:

## Moving State

In the `moving` state the linter tooltip follows the mouse only.

Transition events:
- **Explicit jumps** to a lint will transition the linter to the `jump` state.

## Jump State

In the `jump` state the linter tooltip shows the jumped to lint only. The linter tooltip does _not_ follow the mouse in this state, but instead behave just as if it was in the current _follow keyboard_ mode

Transition events:
- **Cursor moves** will transition the linter to the `moving` state (except for jumps to other lints). Typing will be counted as cursor move too. Placing the cursor with a mouse click will count as cursor move too.

# Open Questions

Atom allows to have multiple panes in split view, each pane can contain multiple tabs, but only one tab per pane will be visible at all times.

This raises the question whether this linter state should be Pane/Tab-global or Pane/Tab-local.

## Pane/Tab-global behaviour

If the linter is in the `moving` state, it will be so for all tabs and panes simultaneously. Only up to one lint will be shown at a time, since there is only own mouse cursor. Mouse over should also show lints in unfocused panes.

If a jump-to-lint occurs, linter will jump to the lint in some tab ins some pane. It will also transition to the `jump` state for all tabs and panes simultaneously. This will show the jumped to lint in the according tab and pane and disable any lints that are caused by a mouse hover.

If a second jump-to-lint occurs, it might jump to it in a different tab - possibly in a different pane in split view. Only the last jumped to lint will be shown - or somewhat equivalently only the lint for the _currently focused_ pane.

Changing focus to another tab/pane (while in global jump state) could trigger a transition to the global move state. I think it's reasonable to argue that changing focus corresponds to a global cursor move.

## vs. Pane/Tab-local behaviour

The linter will have independent states per tab, but start in the `moving` state for each one by default.

If a jump-to-lint occurs, linter will jump to the lint in some tab. It will also transition to the `jump` state for this tab only. This will show the jumped to lint in the according tab. Lints on mouse over will be disabled for this tab accordingly. However it will be possible to show lints in other tabs on mouse over if they are in the moving state.

If a second jump-to-lint occurs, it might jump to it in a different tab - possibly in a different pane in split view. This will not affect whether lints are shown in other tabs, i.e. the lint from the first pane would still be shown.

Changing focus to another tab/pane will not change any linter state, because it does not correspond to a jump to lint or cursor move in a tab/pane-_local_ interpretation.

# Possible Outlook 

An orthogonal future extension of this would be the idea of jumping to the next lint _within visual range_. This would allow a workflow, where you can type and navigate the cursor without the view being obstructed by lints. If you then notice a lint within visual range you have to options to show it (a) switch to the mouse and hover the lint or (b) keep your hands on the keyboard and use the `jump to next lint` shortcut, which should then default to jumping to the next lint within visual range (and showing it).

The `jump to next lint` could respect the newly introduced `moving` and `jump` state and do something clever like this:
- in `moving` state, `jump to next lint` will try to jump to the next lint within visual range.
- in `jump` state, `jump to next lint` will just iterate through _all_ lints in a loop.

This would be very helpful for an all-hands-on-keyboard workflow. I imagine it like this `jump-to-next-lint` shows a lint (`jump` state), you decide to work on it and its hidden (`moving` state). You ask yourself, _what was that lint again?_ and press `jump-to-next-lint` again. Since the lint is still closest in visual range, linter will jump to the _same_ lint again (`jump` state), and once your done reading you can continue coding which will hide it again (`moving` state). 

If this concept of _next within visual range_ is to hard, a simplification would be that `jump to next lint` would actually default to starting with the last jumped-to-lint linter is in the `moving` state and only start iterating over the lints in the `jump` state:
- in `moving` state, `jump to next lint` will
  - jump to the _last_ -jumped-to-lint if that has been set and is still a lint
  - jump to any lint and store it as the last-jumped-to-lint
- in `jump` state, `jump to next lint` will just iterate through _all_ lints in a loop and store it as the last-jumped-to-lint. 

If people like this mode enough, some other "tooltip follows: foo" modes might even be abandoned. However it might be reasonable to have them coexist for a while to collect feedback on their usage.

# Releated

#206 suggests to follow both mouse and keyboard.

**Comment by colin-kiegel** [comment]
@steelbrain I think the proposal I made here is orthogonal to _follow: both_.

Following keyboard tends to obstruct the view while typing. That's why I don't like a mode like follow keyboard or follow both. But I still would like a mode _follow jump to lint_.

Does that make sense? Maybe there could be another mode for _follow jump to lint_ than my proposal.

Could this ticket maybe be reopened just for discussion, or should I open a new ticket?

**Comment by steelbrain** [comment]
If I understand the jump to lint correctly, I think we already have a ton of commands for that.

Please have a look at https://github.com/steelbrain/linter-ui-default/blob/9988655f5b5c5d85903e78975357e01447e55c60/lib/commands.js#L17-L43

You could bind any of these to the keys of your choice.

**Comment by colin-kiegel** [comment]
Yes I know that you can jump to lint's and I use it alot.

But with my configuration I don't see the lint when I jump there, which is a missing feature IMO.

The reason is of course that I disabled _show lints on cursor move_ (or whatever this option is called .. I cannot check that right now, I'm traveling).

All I want is show lints _on jump to lint_, but not show lints _on cursor move_.

**Comment by colin-kiegel** [comment]
For me this would be the sweet spot for my workflow :-)
