### ISSUE TITLE
Slow activation time

### ISSUE THREAD

**Issue by 50Wliu** [steelbrain/linter-ui-default#226]
Currently the second on my list at 240ms (the first one is experimental, so I'd expect that one to be slower).

linter-ui-default@1.2.1, Atom 1.17.0-dev-cebe8adef, Windows 10 x64.

**Comment by 50Wliu** [comment]
Here's a screenshot from a fresh startup.  It's now first on the list by more than 1000ms.
![linter-ui-default-slow-activation-time](https://cloud.githubusercontent.com/assets/2766036/24432892/0ea6a6a0-13f3-11e7-8713-ebc7755ffa89.png)

**Comment by Arcanemagus** [comment]
So in a recent load of `linter-ui-default` that took a total of 600ms, it looks like the majority of the time (451 ms) was spent in requiring the main module, which meant running all the import statements. The `activate()` function itself took 126.8 ms, which is still quite long, but much less than what TimeCop claims to be the activation time.

In the activation itself 121.4 ms was taken up by requiring the `atom-package-deps` module, the call to `install()` from that only took 5.0 ms.

So it looks like lazy requires would be the most beneficial speed up, and delaying the `atom-package-deps` usage till after activation being another possibility.

**Comment by bilderbuchi** [comment]
On starting an Atom instance without any files open, typically `linter-ui-default` has the longest activation time (~300ms), by a factor of ~3 more than the next one (`linter`at ~100ms). Atom 1.15.0, linter-ui-default 1.2.2

**Comment by Arcanemagus** [comment]
As an FYI, I've got a branch that currently drops the activation time by 5x the current, still working on more optimizations though.

**Comment by Arcanemagus** [comment]
~20x current right now, not sure how much more I can do, maybe another 3-4 ms.

**Comment by bilderbuchi** [comment]
Great, thanks!
