### ISSUE TITLE
Decorations add a mysterious "1" to the current line's gutter

### ISSUE THREAD

**Issue by aouaki** [steelbrain/linter-ui-default#229]
Hello,

The selected line has a mysterious "1" in the gutter (as you can see left to the "H" on the screenshot). It disappears when I disable the "Show decorations" option in the package.

![image](https://cloud.githubusercontent.com/assets/9219109/24286309/ecca87a8-1074-11e7-84e5-f5cdbb48a449.png)

In the screenshot, I just created a new file (no type) and added these few lines.

Anyone having the same issue ?

Atom: 1.15.0 x64
OS: Mac OS X 10.11.6

EDIT: I'm using vim-mode-plus and I just discovered that the "1" only appears on Normal mode
#
Thanks!

**Comment by fuddmain** [comment]
I had the same issue.  Are you using the relative-numbers package?  If so, drop this into your style.less:
```
.gutter[gutter-name="relative-numbers"] {
      display: none !important;
}
```
That worked for me.  Funny thing is the relative-numbers package has this set to display:none, but something in linter-ui-default seemed to make it show.

Cheers.

**Comment by aouaki** [comment]
That was a good call, except your style didn't work for me. I finally ended using
```
.custom-decorations .relative {
    display: none;
}
```

The `!important` is unnecessary it seems, but it's solved. I don't have a clue why this error was toggled by this package anyway...
Closing the issue. Thanks @fuddmain !
