### ISSUE TITLE
counts not showing in status bar on macOS

### ISSUE THREAD

**Issue by joeroback** [steelbrain/linter-ui-default#231]
<img width="1920" alt="screen shot 2017-03-26 at 6 17 21 pm" src="https://cloud.githubusercontent.com/assets/156174/24337321/8a85c30e-1250-11e7-99ab-c9370912a596.png">

I cannot get the status bar counts to load. Opening dev console, I see no errors. Opening the same project on Linux works. Unknown how I can debug this. Can I easily turn on linter debugging?

thanks

**Comment by steelbrain** [comment]
Hi @joeroback 

It's not just the Linter status bar that's not showing up, the lin:col and other indicators are invisible too. Can you try switching to a different theme or disabling other packages one by one to see which one is causing the problem?

**Comment by joeroback** [comment]
ah you're right, will do that and report back. thanks!

**Comment by joeroback** [comment]
i guess something was jacked up in my config.. don't have the time to investigate, starting over by removing `.atom` directory and reinstalling was faster, unfortunately. :(
