### ISSUE TITLE
Tooltip overlaps over linter panel

### ISSUE THREAD

**Issue by dbachko** [steelbrain/linter-ui-default#233]
<img width="683" alt="screen shot 2017-03-27 at 12 10 35 pm" src="https://cloud.githubusercontent.com/assets/9260214/24366755/1a3f596e-12e8-11e7-8879-7c1e9a004110.png">

**Comment by steelbrain** [comment]
That's actually an Atom bug, Atom should be hiding the tooltips and putting them BEHIND the panel but it doesn't, sadly.
Did we use to have a workaround for this @Arcanemagus?

**Comment by Arcanemagus** [comment]
Nope, it's always been a bug as far as I know.

**Comment by steelbrain** [comment]
Closing based on above discussion

For the reference, I tried to fix this about 13 months ago and it was closed as a hack, the issue that was opened as an alternative to the hack is still unresolved 😛 https://github.com/atom/one-dark-ui/pull/127 and https://github.com/atom/atom/issues/11249
