### ISSUE TITLE
Panel font size does not adjust with UI

### ISSUE THREAD

**Issue by ribmo** [steelbrain/linter-ui-default#236]
- Platform: Linux
- Atom Version: 1.15.0
- linter@2.1.2
- linter-ui-default@1.2.2

I have my editor font size and my UI font size set larger than default to deal with my kinda-HDPI display.

However, the panel has [a hard-coded 12px font][1] which renders it almost unusable for me:

![screenshot from 2017-03-30 14-01-26](https://cloud.githubusercontent.com/assets/7317426/24485631/2018f9f4-1549-11e7-8bc5-ef176e905a7f.png)

I'm currently overriding the behaviour in `~/.atom/styles.less`:

```css
#linter-panel .sb-table.linter {
    font-size: inherit;
}
```

![screenshot from 2017-03-30 14-00-54](https://cloud.githubusercontent.com/assets/7317426/24485652/3fd4744e-1549-11e7-9b96-a10277fb1185.png)

Is this something you feel should be resolved?

[1]: https://github.com/steelbrain/linter-ui-default/blob/a122ffaa676b6b41b6b2363600870646609a7e19/styles/bottom-panel.less#L6

**Comment by steelbrain** [comment]
We could take the theme variables and subtract instead of having a hard coded value
