### ISSUE TITLE
Wrong height in soft-wrapped line highlighting

### ISSUE THREAD

**Issue by ph0boss** [steelbrain/linter-ui-default#238]
When typing text the current line is highlighted. After the line is soft wrapped the height of highlighting is smaller than the height of line. The highlighting height is restored to a normal value after correcting text in that line.
Here are two screenshots - the first with mismatching heights, the second is after deleting the last space in a line.
Linux Fedora 25 x86_64, atom 1.15.

![screenshot_20170401_173216](https://cloud.githubusercontent.com/assets/19243265/24580000/51c5eb3a-1709-11e7-875f-ddf6ccf28ebe.png)

![screenshot_20170401_173226](https://cloud.githubusercontent.com/assets/19243265/24580005/5e3a2656-1709-11e7-9710-c3f8c7e0fc25.png)

**Comment by steelbrain** [comment]
Oh God, emulating the line highlighting is hard lol.

Thanks for the report 👍 Will fix
