### ISSUE TITLE
Updating to “linter-ui-default@1.2.2” failed

### ISSUE THREAD

**Issue by edarblanco** [steelbrain/linter-ui-default#241]
```
(node:16029) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

npm ERR! file /home/edar/.atom/.apm/sb-react-table/1.0.1/package/package.json
npm ERR! code EJSONPARSE
npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: /home/edar/.atom/.apm/sb-react-table/1.0.1/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/edar/.atom/.apm/_logs/2017-04-05T14_49_12_721Z-debub.log

the log file
[2017-04-05T14_49_12_721Z-debug.txt](https://github.com/steelbrain/linter-ui-default/files/900845/2017-04-05T14_49_12_721Z-debug.txt)
```

**Comment by steelbrain** [comment]
Are you getting this on each retry or just once?

**Comment by edarblanco** [comment]
In every retry, and it is not the first time in version 1.2.0 I do not remember well, it was the same

**Comment by steelbrain** [comment]
<img src="https://cloud.githubusercontent.com/assets/4278113/24752759/c2b0cdfa-1ae8-11e7-94e7-48bca5484cf3.png">

Unable to repro locally, either your Atom installation has a bug or you have a proxy or something. Either way nothing we have control over in this package :)

Closing but feel free to continue discussing

**Comment by edarblanco** [comment]
It's true in part, it's true I'm behind a corporate proxy, but I've always worked well, now after seeing your comment, I did the same, download the package, compile and install it manually, and everything okay, so with this Solved the problem, thanks for everything from Cuba and continue to develop good software.
