### ISSUE TITLE
linter-pydocstyle displays 'Unknown' under Provider

### ISSUE THREAD

**Issue by willfrey** [steelbrain/linter-ui-default#242]
The `Provider` field displays `Unknown` for [linter-pydocstyle](https://github.com/AtomLinter/linter-pydocstyle) instead of something more appropriate.

If this is an issue with linter-pydocstyle and _not_ linter-ui-default, please comment stating such and then feel free to close this. In that case, I'll open an issue with linter-pydocstyle and comment with a reference to it here.

**Comment by willfrey** [comment]
<img width="748" alt="screen shot 2017-04-07 at 2 36 14 pm" src="https://cloud.githubusercontent.com/assets/13784361/24814436/98dbcd2e-1b9f-11e7-9c22-36043ac71f7c.png">

**Comment by steelbrain** [comment]
Hi @willfrey 

You are right, it's an issue with pydocstyle provider, It's not providing the `name` property. It should. Please reopen this in the appropriate repository.

Thanks!

**Comment by willfrey** [comment]
Thanks for the fast reply! I'll do that.
