### ISSUE TITLE
Add icons in bottom status

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/linter-ui-default#243]
Currently, the bottom status is pretty unclear about what it is until you hover it

<img src="https://cloud.githubusercontent.com/assets/4278113/24837347/c64421be-1d4b-11e7-9ba1-8d08630890f0.png">

VSCode does it better, it shows icons in front of each number so it's clear what mean. I've checked the LICENSE of VSCode and it's MIT, so we can steal it from them 😛 

<img src="https://cloud.githubusercontent.com/assets/4278113/24837348/d89e9eca-1d4b-11e7-989a-7e4661f9a783.png">

Also should replace the gutter green dot with something else

**Comment by SpadeAceman** [comment]
Commenting here from #254, would these same icons also be used in the gutter (instead of today's colored dots) to mark each line of code with the relevant info/warning/error indicators?
