### ISSUE TITLE
Cannot create New Folder w/ right click on directory

### ISSUE THREAD

**Issue by thecircleoflifefree** [steelbrain/linter-ui-default#252]
**Problem description:** Cannot create a New folder in the toggle tree view of Atom by right clicking it and selecting New Folder. Once the name of the folder is typed and then hit enter or the plus sign nothing happens.

**How often:** So far, one time issue.
**Where:** On the toggle tree view of Atom
**Steps to recreate:** Right click on root directory> New Folder
**Workaround:** c://> atom --safe
**Fix:** Uninstalled/Installed linter-ui-default
**Research:** 
-https://discuss.atom.io/t/create-new-file-folder-not-working/40076/2  ---- going safe mode
-https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md     ---- going safe mode
-Issues on steelbrain/linter-ui-default
**Conditions:** 
-No other additional plugin beside default ones installed  (besides linter-tidy of course)
-Windows 7 Home Premium SP1 on Toshiba Satellite
-Atom v.1.15.0

**Comment by steelbrain** [comment]
This has been fixed with the Nuclide File Tree compatibility fix in v1.2.4
