### ISSUE TITLE
Increase font size in error table

### ISSUE THREAD

**Issue by cblp** [steelbrain/linter-ui-default#262]
it is hardly readable

**Comment by Arcanemagus** [comment]
Are you on v1.2.3? https://github.com/steelbrain/linter-ui-default/pull/251 which was released in that version makes it so this simply uses the font size from your theme, so if you are up to date then your theme is to blame 😛.

**Comment by cblp** [comment]
1.2.3.

Which theme does allow to change linter messages size?

![2017-04-19 16-16-30](https://cloud.githubusercontent.com/assets/63495/25181943/c9c85904-251b-11e7-9da7-bf3f1b93e90b.png)

**Comment by steelbrain** [comment]
I am not really sure. Can you tell us how you're increasing the font size in the theme in your screenshot? Are you changing color variables in your `styles.less`? If so, make sure to update `@ font-size` variable in your custom styles

**Comment by cblp** [comment]
I used parameter "Font Size" in https://github.com/atom/one-dark-ui#settings to create this screenshot. Other themes doesn't have any parameters.

I don't know what to write in `styles.less` to affect this. I tried `.tool-panel {font-size: 20px;}` but without success.

**Comment by steelbrain** [comment]
I have not yet tested with that config but will do and report back. Also the correct select for it is `.sb-table.linter`, so an example code would look like

```css
.sb-table.linter {
  font-size: 20px !important;
}
```

**Comment by cblp** [comment]
This works for me, even without `!important`. Thanks!

**Comment by Arcanemagus** [comment]
Font size works for me with `material-ui`:
![image](https://cloud.githubusercontent.com/assets/427137/25194317/e99d52a2-24ee-11e7-9339-0a196e1974f6.png)

However `one-dark-ui` _doesn't_ update, I'm guessing they are setting a different variable.

**Comment by Arcanemagus** [comment]
`one-dark-ui` is [_directly_ modifying](https://github.com/atom/one-dark-ui/blob/1704a0c019eda7adad376a553bfdd14994a8674e/lib/main.coffee#L29) the font size through the DOM API, not a LESS variable. 😞

**Comment by Arcanemagus** [comment]
Closing this as there is nothing we can do about it here!
