### ISSUE TITLE
Opening the linter panel opens on all atom instances

### ISSUE THREAD

**Issue by vanossj** [steelbrain/linter-ui-default#263]
_Current Behavior_
When the linter panel is opened or closed, it is opened or closed on all instances of Atom.
This can eat up screen real estate on other instances of atom that are open on separate monitors for reference.

_Expected Behavior:_
linter panel open/closed state should be unique for each Atom instance.

_Environment:_
Linux
Atom 1.16.0 x64
linter v2.1.4
linter-ui-default v1.2.3

**Comment by steelbrain** [comment]
Stay tuned for Docks API integration in https://github.com/steelbrain/linter-ui-default/pull/256

It should solve the per instance hiding/showing

**Comment by steelbrain** [comment]
Fixed in latest release on latest Atom
