### ISSUE TITLE
Tooltips still show despite being disabled

### ISSUE THREAD

**Issue by SavePointSam** [steelbrain/linter-ui-default#264]
## Versions
- macOS: 10.12.4
- Atom: 1.16.0 x64
- linter: 2.1.4
- linter-ui-default: 1.2.3

## Recording
![gif](https://d3dr1ze7164817.cloudfront.net/items/453D3X0m3g2m160a3701/Screen%20Recording%202017-04-19%20at%2009.13%20AM.gif)

## Expected Behavior
That tooltips are never shown as I have them disabled in the UI settings.

## Other
There are no errors in the Atom console. I'd love to help solve this bug and add tests to help catch it in the future, but I'm near end of sprint and super busy right now. If this stays open for a bit I'll try and see if I can post a PR to fix. Thanks for such awesome work!

**Comment by steelbrain** [comment]
Thanks for reporting this, fix is up in https://github.com/steelbrain/linter-ui-default/pull/265
