### ISSUE TITLE
Conflicts in underline

### ISSUE THREAD

**Issue by zenwalker** [steelbrain/linter-ui-default#266]
When I have two errors in same place I also have two overlapping underlines. Maybe you could merge two underlines into one.

<img width="684" alt="screen shot 2017-04-21 at 10 47 10" src="https://cloud.githubusercontent.com/assets/1812128/25268060/f8b6ae2c-267f-11e7-983b-7cf4122f3ce8.png">

**Comment by Arcanemagus** [comment]
Atom handles rendering of the Markers, it would be _incredibly_ complex to manage this here with virtually no benefit.
