### ISSUE TITLE
Warning in Dev-Mode (PropTypes)

### ISSUE THREAD

**Issue by Positive07** [steelbrain/linter-ui-default#268]
When runing in Dev-Mode you can see a warning printed in the console, the warning reads:

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

(Atom 1.17 beta 3, Windows 10 64bits)

**Comment by steelbrain** [comment]
It's a warning coming in from `react-resizable-box` dependency, it'll be fixed once we remove it in favor of the new Docks feature in Atom.

See https://github.com/steelbrain/linter-ui-default/pull/256

**Comment by Positive07** [comment]
Oh that's great! I'm closing this in favor of that then, since I'm trying in 1.17 anyway
