### ISSUE TITLE
Tooltip from linter v1

### ISSUE THREAD

**Issue by sluchznak** [steelbrain/linter-ui-default#272]
Hello!
Please, explain how to return old tooltips from linter v1?

linter-ui-default:
![2017-04-26_10-51-34](https://cloud.githubusercontent.com/assets/4091442/25418547/5d47a340-2a6e-11e7-9221-cb76a1b91f05.png)

Linter v1:
![2017-04-26_10-51-34](https://camo.githubusercontent.com/f37cca581397d3a6ea222f2de6a32f78de75ea92/68747470733a2f2f692e6769746875622d63616d6f2e636f6d2f653864663734663338306465653637323961646638323230383664646131373466326137366331662f363837343734373037333361326632663637363937343638373536323265363336663664326637333639366536343732363537333666373236383735373332663631373436663664326436633639366537343635373232643738366632663732363137373266366436313733373436353732326637333633373236353635366537333638366637343265373036653637)

**Comment by steelbrain** [comment]
Hi @sluchznak

The only way to return to those tooltips for now is to downgrade to an older version. Sorry about that :(. Thanks for using Linter!
