### ISSUE TITLE
Tweak tooltips to be less scary

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/linter-ui-default#273]
Kinda like #267 but for tooltips

All red or all yellow is not good for people with weak hearts, including myself

Current it looks like this

<img src="https://cloud.githubusercontent.com/assets/4091442/25418547/5d47a340-2a6e-11e7-9221-cb76a1b91f05.png" />

I'm thinking it should be

Grey background, with a thick border on the left side of severity (red/yellow/blue). I'm super horrible at paint but here's something so you get the idea

<img src="https://cloud.githubusercontent.com/assets/4278113/25421794/d46b07e2-2a77-11e7-9cc2-35ab6af959ce.png">

**Comment by Positive07** [comment]
Related issues: #219 and #198
