### ISSUE TITLE
Tooltips to disappear if you start typing

### ISSUE THREAD

**Issue by alexrussell** [steelbrain/linter-ui-default#274]
No idea if this is even possible, but it's be nice if the linter UI tooltips could hide when typing.

I like the fact that they now show on mouse cursor rather than text caret placement (though it's still taking a little getting used to), but sometimes my mouse gets left at a certain place, and it makes it difficult to see what I'm typing if I'm typing nearby (or even correcting the mistake in question).

**Comment by steelbrain** [comment]
Really small change but will have big impact in UX. Thank you!

**Comment by steelbrain** [comment]
A fix is up in #275 and will be part of the next release!

**Comment by alexrussell** [comment]
Wow that was fast. Thanks 😃
