### ISSUE TITLE
red wave line under file problem

### ISSUE THREAD

**Issue by ikzjfr0** [steelbrain/linter-ui-default#277]
I upgraded to latest linter-ui-default (1.2.3) under Atom 1.16.0 of MACOS, then comes a issue, which makes me unable to select files in tree view. I can confirm linter-ui-default is the root cause, see attached.

![issues](https://cloud.githubusercontent.com/assets/6456056/25551985/7d0cf2a6-2cd1-11e7-866f-0541abc39062.gif)

let me know if i need to provide more info for tracking down the root cause for this issue

**Comment by Positive07** [comment]
What theme are you using?

**Comment by steelbrain** [comment]
Closing in favor of #278
(I know this was opened before but it has more details)
