### ISSUE TITLE
Conflict with nuclide file tree

### ISSUE THREAD

**Issue by get-trucked** [steelbrain/linter-ui-default#278]
The nuclide file tree does not allow to open files correctly when linter-ui-default is installed, see quote below for what is believed to be the offending element.

Info:
Atom version: 1.16.0
OS: Linux Mint 18
Expected behaviour: be able to open files as with double click and mouse not to bounce around

Quoted from shushz:
"The linter inserts a linter-decoration element that spans the entire height of the file tree and intercepts the on mouse down events. So even though you're clicking outside of the visual underline, it grabs the mouse event, which causes the file-tree think that the underlined element was clicked and not whatever the mouse was pointing at."

From:
https://github.com/facebook/nuclide/issues/1117
https://github.com/facebook/nuclide/issues/1117#issuecomment-297858390

![output](https://cloud.githubusercontent.com/assets/8860623/25507048/adf23594-2b5e-11e7-8eea-539b9f973e23.png)

![output](https://cloud.githubusercontent.com/assets/14492694/25465013/d5cbe0c0-2b53-11e7-858a-5a52d93e2c9d.gif)

**Comment by steelbrain** [comment]
It works correctly on the builtin tree view so it makes more sense for Nuclide to make their TreeView's style compatible with the builtin one.

As a workaround for this issue, you can change `Decorate on Tree View` config to `None`. I'll investigate and see what can be done

**Comment by steelbrain** [comment]
Added a comment on the Nuclide issue, there isn't really anything we can do about this to "fix" in Linter UI. The only appropriate way to fix this is for Nuclide to make their tree view behave like the native one.

**Comment by get-trucked** [comment]
Thanks steelbrain, Ill close this and see if we can get nuclide to look at there file tree to improve compatibility.
