### ISSUE TITLE
Feature Request: Only display panel on files

### ISSUE THREAD

**Issue by Stanzilla** [steelbrain/linter-ui-default#281]
Currently the panel is shown when you are looking at Atom settings, Timecop etc, would be nice to have it only shown on actual files.

**Comment by steelbrain** [comment]
Is this after the most recent update?

**Comment by Stanzilla** [comment]
Yes

**Comment by steelbrain** [comment]
Yeah that's a known issue. The latest release was a beta-ish because it only shows up if you're running Atom Beta. You can track the progress here https://github.com/steelbrain/linter-ui-default/pull/256

**Comment by Stanzilla** [comment]
Alright, thank you :)

**Comment by steelbrain** [comment]
Fix released in latest update
