### ISSUE TITLE
Wavy Underline is difficult to see

### ISSUE THREAD

**Issue by pdxwolfy** [steelbrain/linter-ui-default#284]
Is there some way to change the color to something brighter or do away with the waviness? Dark blue on a nearly black background is hard to see when using a wavy underline; the old solid underline was easier to see.

**Comment by pdxwolfy** [comment]
Talkin about version 1.2.4 here, which just came in on an update.

**Comment by Arcanemagus** [comment]
The line color is based on the message severity, and the color of that comes from the theme you are using (specifically `@background-color-info`, `@background-color-warning`, and `@background-color-error`).

You can see those colors in the Styleguide (Packages -> Styleguide -> Show), for example here are the colors from the theme I use:
![image](https://cloud.githubusercontent.com/assets/427137/25727195/c55d7954-30dc-11e7-8c34-3044693ec12d.png)

As far as allowing the sold underline style I was sure there was an open issue requesting the ability to switch between them but I can't seem to find it right now.

**Comment by pdxwolfy** [comment]
Thanks. I was able to use that info to set up my own theme with a brighter color there, which is better. I'd appreciate the ability to switch between solid and wavy underline; shall I open a separate issue?

**Comment by steelbrain** [comment]
I vote on reverting to solid underlines entire without a config. Please feel free to open a new issue addressing that.

Closing this as this seems to be resolved
