### ISSUE TITLE
[Regression] Panel no longer appearing in v1.4.0

### ISSUE THREAD

**Issue by DaveSeidman** [steelbrain/linter-ui-default#293]
The panel at the bottom of Atom is not appearing with the latest version of linter-ui-default (1.4.0) but works correctly in v1.2.4

![screen shot 2017-05-16 at 5 42 02 pm](https://cloud.githubusercontent.com/assets/975822/26129634/0caab318-3a5f-11e7-9e59-44d762788148.png)

When placing the cursor over the offending sass I can still see the lint warnings and errors but attempting to open the panel by clicking on the number of warnings or errors raises the TypeError in the attached screenshot.

Thanks in advance!

_Environment_
Mac OS v 10.12.4
Atom 1.17.0-dev-bc8d961
linter 2.1.4
linter-ui-default-1.4.0
linter-sass-lint 1.7.4

**Comment by steelbrain** [comment]
Fix just landed in master, should be in the next release

**Comment by steelbrain** [comment]
v1.5.0 is out with the fixes
