### ISSUE TITLE
Error line link is now broken - clicking fails to jump to error line

### ISSUE THREAD

**Issue by boazsegev** [steelbrain/linter-ui-default#294]
Up until the latest update, clicking the message or the line number would move the cursor to the error's position in the file...

...However, with the latest update (Atom 1.17.0 and linter-ui 1.4.0), this is no longer the case.

Now, when I clock on the error line, all the error messages disappear, the focus is moved away from the open file and no data is displayed.

Re clicking on the open file (the main editor widow) reveals the missing error messages, but clicking the messages seems to be broken.

**Comment by steelbrain** [comment]
Hi @boazsegev 

The docks API has some limitations so you could disable `hidePanelUnlessTextEditor` config until we figure out how to deal with this

**Comment by boazsegev** [comment]
Thanks @steelbrain !

That was super quick... Wow!

**Comment by EvNaverniouk** [comment]
This is still "somewhat" broken for me. I need to click on the panel twice to get it to jump to the line.
