### ISSUE TITLE
Make panelHeight apply live

### ISSUE THREAD

**Issue by pingshunhuangalex** [steelbrain/linter-ui-default#295]
Hi @steelbrain 

I noticed that the `panel height` option has already been removed in the settings (probably due to the new dock feature?) However, without this option, the linter panel now only seems to just take the height of one error, now matter how many errors there are... And the linter panel doesn't seem to remember the position I set previously. Is there a way to bring the option back?

![image](https://cloud.githubusercontent.com/assets/17170199/26134312/11daa5e0-3af1-11e7-84c3-3716dbc9090d.png)

**Comment by steelbrain** [comment]
Hi @pingshunhuangalex 

Thank you so much for reporting this. Unfortunately the Docks API has some limitations but we're working on that. Meanwhile you can use the edge of the Dock (the top purple part) to resize the bottom Dock and with it, The Linter Panel.

Atom should remember this configuration per project.

We could bring back the old panel but Docks are the way forward, they are the only way users can show multiple icons at once simultaneously and save space. 

Also not sure if you know but you can now drag/drop the linter panel anywhere in the UI so that's kinda cool 😛

**Comment by pingshunhuangalex** [comment]
Thanks @steelbrain for the opportune response as always.
I tried resizing the bottom dock in different projects, and it doesn't remember the height. I may have jumped to the conclusion there as I haven't checked if it can be remembered in the same project.

Meanwhile, I still think it would be nice if we can unify the height of the lower dock across various projects, but thanks for the explanation.

P.S. I noticed we can now drag/drop linter panel. It's really handy :)

**Comment by steelbrain** [comment]
> Meanwhile, I still think it would be nice if we can unify the height of the lower dock across various projects, but thanks for the explanation.

I couldn't agree more. The Atom core actually handles the height of docks so we could contact them or I'll hack around inside this package, definitely something on my earliest-todo lists

**Comment by pingshunhuangalex** [comment]
Thanks @steelbrain 
BTW, I just tried resizing the bottom dock in the same project (same file actually). If all the errors are fixed -> linter panel (bottom dock) hides itself -> and when it gets triggered again by other lintering errors, the height won't be remembered. Definitely an Atom Core issue.

Thanks again and keep up the excellent work 🥇

**Comment by steelbrain** [comment]
I've re-added it in https://github.com/steelbrain/linter-ui-default/pull/297 btw
Should be in a release in a day or two

**Comment by pingshunhuangalex** [comment]
Hi @steelbrain 
I don't know what you did, but my atom can now remember bottom dock height without any problems. However, the height option you added back to the package doesn't actually do anything...

Is this an expected behavior? Thanks.

**Comment by steelbrain** [comment]
Hi @pingshunhuangalex 

I was rushing for the fixes so the line height option doesn't update live, so you have to restart Atom to apply it's effects or you could try to resize the panel and it'll save it's height and automatically set height to that the next time it's opened

**Comment by pingshunhuangalex** [comment]
Mmm, it's not quite what happening here...

I tested it by restarting or resizing, but the height option just doesn't do anything. However, the bottom dock height does get remembered now across all projects, even restarting atom or switching projects back and forth.

In short, setting the height number manually in setting won't work even with a restart, but resizing dock by hand does get remembered across projects. Thanks.

**Comment by steelbrain** [comment]
> I tested it by restarting or resizing, but the height option just doesn't do anything. However, the bottom dock height does get remembered now across all projects, even restarting atom or switching projects back and forth.

Hmmm, that's because when you close Atom, your custom added height is again overwritten by the panel's current height, so live updates are the only fix

**Comment by pingshunhuangalex** [comment]
Hi @steelbrain 
When I'm syncing my atom setting today, I noticed the panel height specified got changed to some other values, and when I'm trying to change the value back, atom wouldn't respond (both with/without restart), i.e. the `panel height` config has stopped working again. Thanks.

**Comment by steelbrain** [comment]
Oh boy 😅 

Thanks for reporting

**Comment by pingshunhuangalex** [comment]
Hi @steelbrain 
Just checking if this issue is still on your list? I still got this package constantly overwriting my set panel height. Thanks.

**Comment by pingshunhuangalex** [comment]
@steelbrain 
I noticed something else (maybe), the number gets reverted back only after `linter-ui-default` or maybe atom update.

Every time the setting gets "refreshed", the panel height will always become 131px. Does this number mean anything to you? Together with the panel height, the show panel option will also be unticked.

Hope, this shed more line to the case. Thanks.

**Comment by steelbrain** [comment]
Thanks for the continued details @pingshunhuangalex 

A fix for this issue is up in https://github.com/steelbrain/linter-ui-default/pull/411
