### ISSUE TITLE
Linter panel loses content on click in linter-ui-default 1.4.0 and 1.5.0 on atom 1.17.0

### ISSUE THREAD

**Issue by Rotonen** [steelbrain/linter-ui-default#305]
I have set my linters to only show results for the current file. This leads to a situation in atom 1.17.0 and both linter-ui-default 1.4.0 and 1.5.0 where clicking on the result (and the line number thereof to go to the result) where the editor loses focus, the linter panel loses content and the click lands on the now empty linter panel.

**Comment by steelbrain** [comment]
Will investigate

**Comment by jdmartin** [comment]
I just wanted to chime in to say that I'm having this problem, too.  Same setup as above.  I've also noticed (after 1.5.0) that if I close the panel, it can't be reopened until Atom is restarted.  

Thanks for all your hard work! 😄

**Comment by steelbrain** [comment]
Hi @jdmartin

It's actually there most of the time, just collapsed. You can move your mouse over to the bottom center of the screen and expand it, tho I'll look into fixing that as well

**Comment by jdmartin** [comment]
Cool, thanks.  I think the panel issue might be something else.  I've just had it happen with my tree view, as well.  So, probably no need to worry about that part.  Thanks!

**Comment by jdmartin** [comment]
If it helps, I've made a small screen recording of the problem: [link](https://www.dropbox.com/s/1ite7xnjc4gujwg/linter-ui-bug.webm?dl=0)

**Comment by muppetjones** [comment]
Version 1.3 seems to work. Version 1.4 has the old (I prefer it) style in the status bar, but still doesn't work.

**Comment by steelbrain** [comment]
Should be fixed in v1.5.1

**Comment by muppetjones** [comment]
@steelbrain Still broken in 1.15.2.

**Comment by steelbrain** [comment]
Well try 1.5.4 then instead haha. These docks have been a mess to deal with

**Comment by jdmartin** [comment]
All better over here!  Thanks for the quick fix. 😸

**Comment by ynsta** [comment]
Hi @steelbrain, I have the same issue with version 1.6.1.

I can't clic on lint error lines because when I do that the content of linter disappear.

**Comment by steelbrain** [comment]
@ynsta It's an issue with Atom Docks, change your Panel Represents config to Entire Project
