### ISSUE TITLE
1.5.4 on Atom 1.17.0: linter panel won't remain open

### ISSUE THREAD

**Issue by pdxwolfy** [steelbrain/linter-ui-default#308]
After opening the linter pane, it disappears if I switch to another open file, or another pane. To reopen the linter pane, I have to find and click the open pane thingamajig, and then rerun linter.

**Comment by steelbrain** [comment]
Hi @pdxwolfy 

It collapses the dock that you can expand by moving your mouse to the bottom center and clicking the expand ribbon
<img src="https://cloud.githubusercontent.com/assets/4278113/26179553/d02d741e-3b7d-11e7-900e-ad9376c04451.png">

You can also disable the `hidePanelWhenEmpty` config to disable auto-hiding

**Comment by pdxwolfy** [comment]
Ah, I fixed the issue I was seeing by enabling show panel in the settings. (The problem was that the dock was auto-collapsing when show panel was off, and not reopening when I tried to rerun the linter.)

Frankly, this new Atom pane interface is a mess. Not your fault, of course.

**Comment by steelbrain** [comment]
Thank you for your continued faith, patience and understanding. Glad you found the fix 👍

**Comment by christroutner** [comment]
For those who find this Issue trying to solve the same problem, here are the steps I had to take to fix the problem:

1. Click Edit -> Preferences
2. Click on the `Packages`
3. Search for `linter-ui-default`
4. Click on `Settings` button
5. Ensure the `Show Panel` checkbox is checked.
