### ISSUE TITLE
Panel should respect white-space.

### ISSUE THREAD

**Issue by omeryagmurlu** [steelbrain/linter-ui-default#312]
### Current Behaviour:
Whitespace is not respected.

![2017-05-18-182250_1158x83_scrot](https://cloud.githubusercontent.com/assets/8201544/26210361/fd8e0c8c-3bf7-11e7-9b72-99acc88a39b6.png)

### Suggested Behaviour:
Whitespace is preserved as it is in the output.

![2017-05-18-182212_1160x189_scrot](https://cloud.githubusercontent.com/assets/8201544/26210287/cb9fd4d0-3bf7-11e7-969f-e709fd79e296.png)
```
#linter-panel {
	tbody {
		font-family: monospace;
		white-space: pre-wrap;
	}
}
```

**Comment by steelbrain** [comment]
That's a bug in ESLint. Providers should not provide more than one line, ever, in excerpt. Fix is pending merge in https://github.com/AtomLinter/linter-eslint/pull/911
