### ISSUE TITLE
Duplicate Linter tabs in Dock

### ISSUE THREAD

**Issue by akonwi** [steelbrain/linter-ui-default#314]
Atom v1.17.0
Mac OS Sierra 10.12.4

Lint packages installed:
- linter 2.1.4
- linter-eslint 8.17
- linter-ui-default 1.5.4

On startup of atom, there are two tabs titled 'Linter' in the bottom dock.

<img width="1838" alt="screen shot 2017-05-18 at 11 46 02 pm" src="https://cloud.githubusercontent.com/assets/2013804/26233642/85e1801a-3c24-11e7-9b7b-2f9195df0d0f.png">

Also Clicking anything inside the dock triggers it to close.

![atom-linter](https://cloud.githubusercontent.com/assets/2013804/26233901/49422a22-3c26-11e7-8cc8-e0f91e46702c.gif)

**Comment by grantstephens** [comment]
I have the same.
Since upgrade to v1.17.0

**Comment by akonwi** [comment]
__Update:__ It seems when there is content in the linter tabs because of a lint error, then the dock is actually interactive. I have lint on save enabled and if the active tab inside the dock is not a linter tab, then when I save and the lint errors get fixed, the dock closes. I would expect it to stay open because another tab is in focus

**Comment by Arcanemagus** [comment]
@akonwi Closing when there are other tabs in the Dock is a separate issue, can you file that as well?

**Comment by akonwi** [comment]
This seems to be fixed with the latest update.
