### ISSUE TITLE
'fix line' tooltip

### ISSUE THREAD

**Issue by giolf** [steelbrain/linter-ui-default#316]
The demo show that it's possibile to do `fix es issue`:
![image](https://cloud.githubusercontent.com/assets/4278113/23875866/cdd051fe-085c-11e7-81c9-89fa59456891.gif)

but me i don't have that option.  
Maybe i've to some options in the settings?

thx

**Comment by giolf** [comment]
Solved: just check the `intentions` package. the default keymap on OSX is `ctrl + enter`

**Comment by steelbrain** [comment]
Glad you found it 👍
