### ISSUE TITLE
Does not play nice with other docked panels

### ISSUE THREAD

**Issue by ProPuke** [steelbrain/linter-ui-default#322]
Currently, linter [automatically hides the dock container](https://github.com/steelbrain/linter-ui-default/blob/master/lib/panel/index.js#L80) if another pane is focused (and `hidePanelWhenEmpty` is set).

Please do not do this. Other things use the bottom dock too and this makes it unusable :/

If I interact with a pane on the bottom dock linter will instantly hide it upon click (because it's being focused).
If I'm using a pane on the bottom dock and then click elsewhere linter will close the bottom dock, even if linter is not the pane being used. This is rude :(

If you want to automatically hide the linter panel, I'd recommend `destroy()`ing it instead, and then recreating it when it's wanted. Do not forcibly hide the dock container as this interferes with other panes also using it.

Thanks

**Comment by steelbrain** [comment]
Yep, expect a fix real soon, I'm woking on the issues right now

**Comment by ProPuke** [comment]
Awesome. Cheers!
