### ISSUE TITLE
Dock is not interactive while there are other tabs

### ISSUE THREAD

**Issue by akonwi** [steelbrain/linter-ui-default#328]
Atom v1.17.0
Mac OS Sierra 10.12.4

Lint packages installed:

- linter 2.1.4
- linter-eslint 8.17
- linter-ui-default 1.5.4

While there is another non-linter tab in the dock, any clicks inside the dock cause it to close.

![atom-linter](https://cloud.githubusercontent.com/assets/2013804/26233901/49422a22-3c26-11e7-8cc8-e0f91e46702c.gif)

It seems when there is content in the linter tabs because of a lint error, then the dock is actually interactive.

**Comment by steelbrain** [comment]
Hi @akonwi 

Can you disable `hidePanelWhenEmpty` config and see if that fixes the behavior?

**Comment by akonwi** [comment]
Yea that works! I totally missed that option before
