### ISSUE TITLE
Statusbar style changed?

### ISSUE THREAD

**Issue by austinbutler** [steelbrain/linter-ui-default#329]
At first I thought it was maybe a bug, but now I am wondering whether it's intentional. At any rate, the previous indicator for linter issues (as seen on the current readme for this project) were really slick! The new ones get the job done, but they seem to take up more space and look messier.

![image](https://cloud.githubusercontent.com/assets/354741/26331879/3c36e496-3f08-11e7-95e5-cf5ae0ad22e9.png)

**Comment by Arcanemagus** [comment]
Are you talking about the addition of the icons? Before those were added it was just numbers there. The icons themselves come from your theme.

**Comment by austinbutler** [comment]
It's more than adding icons, it's removing the boxes as well. I tried reverting to the stock Atom theme and it stays the same, just as in my screenshot above. Also on the same theme previously it did look exactly like in the readme GIF, no icons.

**Comment by Arcanemagus** [comment]
The issue was raised by many other people that it was impossible to distinguish visually what each number meant, especially for color blind people. The icons were added to match several IDE's style of including this information.

**Comment by austinbutler** [comment]
I see, not a problem then. Thanks!
