### ISSUE TITLE
Add new option to "Tooltip Follows" (or change existed behavior for `Keyboard` option)

### ISSUE THREAD

**Issue by nodkz** [steelbrain/linter-ui-default#330]
<img width="460" alt="screen shot 2017-05-23 at 16 48 41" src="https://cloud.githubusercontent.com/assets/1946920/26351202/6d788818-3fd8-11e7-9192-1b49f243e143.png">

Right now with enabled option `Keyboard` (also `Both` option is affected), error hint displaying is too annoying. It popups on every key-press and in 90% shows me parsing error or assigent/function call:

<img width="773" alt="screen shot 2017-05-23 at 16 59 27" src="https://cloud.githubusercontent.com/assets/1946920/26351423/7177248c-3fd9-11e7-9dbf-785a8cb7a643.png">

<img width="612" alt="screen shot 2017-05-23 at 17 00 32" src="https://cloud.githubusercontent.com/assets/1946920/26351458/95b91a62-3fd9-11e7-82ff-f5f076431911.png">

My suggestion is to create a new option `Keyboard on Move/Navigate` or modify existed `Keyboard` behavior which will show tooltip only if:
- the last pressed key was UP, DOWN, LEFT, RIGHT, PAGE_UP, PAGE_DOWN
- ignore all other characters

It makes code typing more convenient with keeping the ability for viewing errors when press arrow keys.

**Comment by steelbrain** [comment]
Hi @nodkz 

You can disable lint on change configuration to make it a little more convenient for you. On our part, I think we could not show a new tooltip on the point of cursor when tooltip setting is set to follow keyboard so users don't see an annoying tooltip while writing. Thoughts @Arcanemagus?

**Comment by Arcanemagus** [comment]
On the surface your suggestion sounds reasonable @nodkz, I'd like to hear from at least one other person that uses "follows keyboard" though since I myself don't.

An alternative to completely disabling on-change linting is to bump up the delay before a lint is triggered, I use 1500 ms myself.

**Comment by nodkz** [comment]
Wow, @Arcanemagus thanks for the hint about `300ms` -> `1500ms` in `linter` package. It was too low value for me also. Now much better. This option is not well advertised. And maybe required other higher default value for providing better performance and removing annoying on-change linting.

But anyway, this issue is still actual. 
Waiting for other people's thoughts...

**Comment by mikebronner** [comment]
I'm having this issue as well. What do you think about adjusting this behavior to lint when typing ceases, but hide the hint while actively typing?

**Comment by fpuga** [comment]
I agree with the usability issues described by @nodkz and @mikebronner 

Basically, the tooltip is very distractive to me, and in many cases, you already know what the error is about, so, the tooltip is not needed. So I have it only enabled to follow the mouse. But sometimes is annoying having to leave the keyboard to see the tooltip. As it's suggested in #347 it will be awesome having a keybinding to show the tooltip of the current line as `linter-ui-default:expand-tooltip` does not show it.

**Comment by steelbrain** [comment]
This issue has actually been implemented, the default value for `TooltipFollows` now supports `Mouse`, `Keyboard` and `Both`. Both being the default, which listens for both the mouse and keyboard movements.

@fpuga Could you open a separate issue about that?

**Comment by mikebronner** [comment]
@steelbrain I think the issue is here that the tooltip does not go away when you type if the mouse cursor is still over the line.

**Comment by fpuga** [comment]
Thanks for reviewing this @steelbrain and sorry for the noise. I open a separate issue #403

**Comment by steelbrain** [comment]
@mikebronner It does now in latest release with Both as tooltipFollows

**Comment by mikebronner** [comment]
@steelbrain Ah, thank you for clarifying that it was a recent update! :) Will have to try again, wasn't paying attention. :)
