### ISSUE TITLE
Missing `Always Take Minimum Space`

### ISSUE THREAD

**Issue by augusto-moura** [steelbrain/linter-ui-default#331]
Where is the `Always Take Minimum Space` option? I looked in the changelog and didn't find any mention of a removal. There is a reason for removing it?

**Comment by steelbrain** [comment]
Hi @augusto-moura 

That option has been renamed and reimplemented for Docks API Support. You'll now see it as `hidePanelWhenEmpty`

**Comment by augusto-moura** [comment]
There's a way of defining it to be the minimum possible? The Linter dock seems to have a fixed height, adding a blank space when the errors height don't reach the `Panel Height`

**Comment by adamreisnz** [comment]
I think this is related to #332 -- `hidePanelWhenEmpty` does not seem to be the same as `always take minimum space`. The panel needs to resize and get smaller automatically when there are errors, but when they're not taking up the full space of the panel.
