### ISSUE TITLE
Clicking the Linter window makes the text disappear

### ISSUE THREAD

**Issue by Cole128** [steelbrain/linter-ui-default#334]
I created an issue [here](https://github.com/steelbrain/linter/issues/1473), they told me to come here.

**Comment by steelbrain** [comment]
Do you have the `hidePanelWhenEmpty` config enabled by any chance? If you have, you shouldn't be hiding/showing panel yourself. If you want to hide/show panel yourself, please disable that config and see if the behavior is fixed

**Comment by Cole128** [comment]
Well now all it does is pop down again instead of making my cursor go to the line.

**Comment by Cole128** [comment]
K thanks
