### ISSUE TITLE
How to customize status bar style

### ISSUE THREAD

**Issue by gmourasilva** [steelbrain/linter-ui-default#335]
Hi

Sorry for using this channel for this maybe stupid question, but how can I customize the error/warning/info numbers in the status bar?

I'm using everything updated and this is what I am getting:

<img width="103" alt="screen shot 2017-05-25 at 11 37 50 pm" src="https://cloud.githubusercontent.com/assets/19296961/26483755/87dbd080-41a3-11e7-9cd4-b8bde899ee77.png">

I tried to downgrade packages, took a look in the status-bar package, tried different themes and none of those options get me the background color from your readme:

<img width="72" alt="screen shot 2017-05-25 at 11 41 15 pm" src="https://cloud.githubusercontent.com/assets/19296961/26483808/c1508a04-41a3-11e7-80d1-20e675614b4f.png">

Any thoughts to share? 

Thanks

**Comment by steelbrain** [comment]
Hi @gmourasilva 

The old bar has been removed in favor of the new one, because some people are color blind and also because new comers don't know what that 3 in the box means until they hover it. Though if you have any suggestions to make the current bar look better, please let us know :)

**Comment by gmourasilva** [comment]
Hi @steelbrain 

Thanks for the fast response. 
For me this new one is so minimalist. 

How can I hack this CSS? Is it possible I override in my local Atom?

**Comment by johnschult** [comment]
>   ```css
>   .icon {
>     display: none;
>   }
> ```

Use this now instead:

```css
  .icon-stop::before, .icon-alert::before, .icon-info::before {
    display: none;
  }
```
