### ISSUE TITLE
Why i need to click 2 times on the line number to move to the next error instead of just 1 time?

### ISSUE THREAD

**Issue by AionDev** [steelbrain/linter-ui-default#341]
Version number is `1.6.0` 
First thanks for building this package. Compared with what i used before - is life changing 😄 Especially in elm - a language with friendly compiler messages.

After the last update i have experienced this wired behavior. Is not that bad - but with lot's of errors it becomes annoying. 

I need to click 2 times on the line number before jumping to the next issue. 

And also looks like the padding on the element is not big enough. I want to have room space - if i click 1-2 mm away - still i want the clicking action to be picked up. There is plenty of space for 5 -10 px padding on all sides.

I don't think this is hard to do and will provide a much user better experience. I can't record the mouse clicks on a gif - sorry. I've attached a normal image.
![why i need to click 2 times inside ui-default-linter](https://cloud.githubusercontent.com/assets/20288140/26684911/3ca21072-46f1-11e7-8fe5-103b94cc26b1.png)

**Comment by steelbrain** [comment]
Hi @Aion-github

Can you show us a screenshot of your Linter UI Default config?

**Comment by DahliaSR** [comment]
I am having the same problem on Win 7.

The double click also works in the description column, but the cursor does not change, to indicate that this is possible, the cursor also only changes when hovering over text.
Double clicking in another columns than **Description** or **Line** does have no effect.  
It would be nice to have the whole line of an entry clickable and the the cursor changing even if not over text.

Here are my **linter-ui-default** settings:

![image](https://cloud.githubusercontent.com/assets/19154016/26695571/9c878cbe-470b-11e7-8d58-606997a82073.png)
![image](https://cloud.githubusercontent.com/assets/19154016/26695595/b010ae78-470b-11e7-92c3-e1c07975ac02.png)

**Comment by steelbrain** [comment]
Can you disable `hidePanelWhenEmpty` and try it again and see how it goes?

**Comment by DahliaSR** [comment]
@steelbrain 
> Can you disable hidePanelWhenEmpty and try it again and see how it goes?

I tried it and it besomes even worse.

When clicking , either in **Description** or **Line** column, the table in the clears and the status bar disappears.  
When I hide the **Dock Panel**, the table and status bar directly show up again.

After that, I enabled `hidePanelWhenEmpty`, again and it behaved as it usually does.

##### Before clicking:

![image](https://cloud.githubusercontent.com/assets/19154016/26741159/8e3ab032-47d8-11e7-92d8-434b51de421c.png)

##### After clicking:

![image](https://cloud.githubusercontent.com/assets/19154016/26741198/af62734e-47d8-11e7-94b2-7d71403ec22c.png)

**Comment by DahliaSR** [comment]
Follow up...

It might be a **Focus** problem.

Toggling the panel to visible **does not** put it into focus, so the first click moves the focus to the panel and the second click fires the event.

**Comment by DahliaSR** [comment]
@steelbrain 
2nd Follow-up...

Tjis no longer is an issue with **linter 2.2.0** and **linter-ui-default 1.6.10**, it works exactly the way expected.

**Comment by Arcanemagus** [comment]
Nothing was changed related to that, I wonder if you had some other package that was interfering? In any case as @AionDev hasn't been responding I'm just going to mark this as closed for now. Thanks for reporting back @DahliaSR!
