### ISSUE TITLE
Black bar in atom light ui

### ISSUE THREAD

**Issue by fabianfiorotto** [steelbrain/linter-ui-default#344]
This bar appears sometimes when I move the mouse to the bottom. It seems like disabling this packages fixes it. I'm using atom 1.17 
![screenshot at 2017-06-02 10 28 43](https://cloud.githubusercontent.com/assets/898842/26728289/2625505e-4780-11e7-9ec3-e620ce369ba7.png)

**Comment by Arcanemagus** [comment]
This is actually a bug in Atom v1.17 itself and has nothing to do with this package (other than this package uses the bottom Dock). Unfortunately I don't think this will be fixed till Atom v1.19 as if I remember it's a bug in the underlying version of Chrome.

**Comment by fabianfiorotto** [comment]
The bottom dock works ok when I disable this packages. Has it been reported in atom? Do you know the issue number?

**Comment by steelbrain** [comment]
Hi @fabianfiorotto 

Fly-by comment on why it appears only when linter is active, it's because you don't have any other package using the bottom dock part of Atom. You could try with another package like `atom-terminal-tab` and see if it only happens with linter or any other packages using docks

**Comment by Arcanemagus** [comment]
@fabianfiorotto Do you have the `atom-material-ui` theme installed? I just was tracing down the exact causes of this in order to file a bug and found I could only replicate this when that theme was in use. I'll be filing an issue there about this.

**Comment by fabianfiorotto** [comment]
No. I installed it to test a thing in my own package. But I deleted it after that.

**Comment by Arcanemagus** [comment]
As an FYI, turns out that I'd only imagined that issue already being filed, so I filed https://github.com/atom/atom/issues/14915 to get this fixed in Atom.
