### ISSUE TITLE
Invalid position of the "docker handle" and "error panel" when [status-bar > Full-width] is set to OFF

### ISSUE THREAD

**Issue by UmkaDK** [steelbrain/linter-ui-default#346]
# Current setup

- Atom version info (`atom --version`)
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

- linter-ui-default version
1.6.0

- OS
macOS Sierra 10.12.5

- Settings:
  - [Packages > status-bar > Full-width] is set to OFF

# What I expect to happen
I expect the docker handle for the error panel and the panel showing all errors to appear above the status bar, the same as it does the [Packages > status-bar > Full-width] is set to ON, eg:

- Docker handle
<img width="372" alt="docker-handle-ok" src="https://user-images.githubusercontent.com/2833247/26874107-4b013634-4b74-11e7-86cb-f9f5bb86231a.png">

- Error pannel
<img width="364" alt="error-panel-ok" src="https://user-images.githubusercontent.com/2833247/26874119-546ae9ea-4b74-11e7-9c28-92ee523cb6b4.png">

# What actually happens
The error panel appears below the status bar, and the docker handle overlaps the status bar.

- Docker handle
<img width="312" alt="docker-handle-err" src="https://user-images.githubusercontent.com/2833247/26874147-6824ee72-4b74-11e7-800f-df43b022017c.png">

- Error panel
<img width="460" alt="error-pannel-err" src="https://user-images.githubusercontent.com/2833247/26874156-7464eaca-4b74-11e7-9cf0-a441e0e6c962.png">

**Comment by Arcanemagus** [comment]
This is an Atom bug, this package has nothing to do with the way the Dock itself works. You might try searching the [status-bar](https://github.com/atom/status-bar) issues since you mention changing one of it's settings affects this.
