### ISSUE TITLE
linter-ui-default 1.6.1 seems to have a regression which causes goto line number to break

### ISSUE THREAD

**Issue by cenkentimist** [steelbrain/linter-ui-default#353]
Previously a similar (possibly the same issue) was discussed here https://github.com/steelbrain/linter/issues/1467#issuecomment-302194933
When I try to click on a line number the items in the table disappear.
nothing is logged to the console though.

**Comment by steelbrain** [comment]
Found the Atom bug, fix will be in next stable hopefully https://github.com/atom/atom/pull/14695

**Comment by cenkentimist** [comment]
The latest version of atom(1.18.0) seems to fix the problem I'm having. I probably should of tested it as soon as it came out. Sorry for taking up your time.
