### ISSUE TITLE
Tooltip obstructs autocomplete+ suggestions

### ISSUE THREAD

**Issue by zmb3** [steelbrain/linter-ui-default#354]
The tooltip that shows lint warnings obstructs the autocomplete plus suggestions.

![image](https://user-images.githubusercontent.com/7527103/27157767-f1e970d8-5128-11e7-9c19-0973a9c71588.png)

This results in a poor experience when using linters that lint on the fly.   Can we adjust the zIndex such that the linter tooltip is underneath the autocomplete suggestions?

**Comment by steelbrain** [comment]
Are you on the latest version? Did you move your cursor over there after the autocomplete box popped up?

**Comment by Arcanemagus** [comment]
On the latest version, and the cursor was already there (in the middle of typing). Since the marker follows the `)` automatically, it never closes leading to the top autocomplete suggestion being blocked.

**Comment by steelbrain** [comment]
Workaround: Change tooltip follows config to `Mouse`

**Comment by lukescott** [comment]
@steelbrain The fix is moving the mouse, correct? What if you are mostly a keyboard user?

**Comment by steelbrain** [comment]
@lukescott This was actually fixed for keyboard users where it would hide automatically and not show up when writing text, recent Atom + autocomplete-plus seems to have changed the core behavior and broke it. You can track it at https://github.com/steelbrain/linter-ui-default/issues/415

**Comment by lukescott** [comment]
Awesome, ty!
