### ISSUE TITLE
Update 1.6.2

### ISSUE THREAD

**Issue by Eremiteb** [steelbrain/linter-ui-default#374]
Atom 1.18.0 x64 on Windows 7 x64.
I'm trying update linter-ui-default, but received a mistake: Unable to download... unable to verify the first certificate
I have removed and has tried to establish anew, but now it just isn't established.
The same in updating attempt linter 2.1.4 to 2.2.0

**Comment by steelbrain** [comment]
Closing in favor of https://github.com/steelbrain/linter/issues/1505
Both are the same issue
