### ISSUE TITLE
Change background of the whole linted line

### ISSUE THREAD

**Issue by tuxmark5** [steelbrain/linter-ui-default#376]
I've been looking for a way to change the background color of the whole line when the line is linted with a build error. I'm using atom-build and it is very difficult to quickly see where the errors happen, as the puny red dot is not that visible. It that possible to do this with the current version of linter?

**Comment by steelbrain** [comment]
You could pair up with minimap-linter, while keeping an eye on bottom status and tree-view. You could also enable panel and set it to represent Current File and then click on errors.

Background highlighting the whole line would look really intrusive and not to mention the inversion of syntax colors, I am personally against it

**Comment by tuxmark5** [comment]
At very least I'd like to underline the line. As the red dot is practically invisible.

**Comment by steelbrain** [comment]
We do actually underline it
![screen shot 2017-06-29 at 2 58 36 pm](https://user-images.githubusercontent.com/4278113/27712345-7ce6e6e4-5cdb-11e7-8b8a-af330c7d6dd7.png)

Make sure you have this option enabled in linter-ui-default

![screen shot 2017-06-29 at 2 59 18 pm](https://user-images.githubusercontent.com/4278113/27712362-90177ab2-5cdb-11e7-968e-d8a95684fdd7.png)

**Comment by tuxmark5** [comment]
Decorations are enabled, but no underline of any kind in sight.

**Comment by steelbrain** [comment]
Can you report your Atom and package versions? Also a screenshot of dot but no underline would be very helpful

**Comment by tuxmark5** [comment]
Here's the screenshot: https://imgur.com/a/4FogE
Atom version: 1.18.0
Packages:
* build 0.68.0
* linter 2.2.0
* linter-ui-default 1.6.2

**Comment by steelbrain** [comment]
The build package is providing a zero width range therefore we are not highlighting anything, it could provide a `[[row, 0], [row, Infinity]]` range then linter would underline the entire row.

Please reopen this in the build package, also thanks for providing the useful info so quickly, a rare sight 👍

**Comment by tuxmark5** [comment]
No worries, thank you for the really quick responses.
