### ISSUE TITLE
"Show panel" option in settings won't stay turned off

### ISSUE THREAD

**Issue by ithuvanian** [steelbrain/linter-ui-default#379]
I'm not able to stop the error panel from automatically appearing on the bottom of the screen. I keep unchecking the "show panel" box in settings, which only works temporarily. Before long the panel starts popping up again whenever I switch to view a new file, and when I check my settings I find that the box has automatically checked itself again. This seems to happen after I've pulled up the panel on my own by clicking the arrow on the bottom of the window, but it doesn't necessarily happen the first time I do so. (Atom version 1.18.0 on Ubuntu 16.04)

**Comment by Arcanemagus** [comment]
If you have the "Hide Panel When Empty" setting enabled (default) then the Panel will automatically toggle based on whether there are messages to show... although I'd say that the "Show Panel" option should override it if it doesn't currently.

**Comment by ithuvanian** [comment]
Yes the "show panel" option does override it- the problem is that "show panel" was not staying disabled for me.

**Comment by Arcanemagus** [comment]
There are only [two](https://github.com/steelbrain/linter-ui-default/blob/185776716a33523359778c01c92216a5fbcbc005/lib/commands.js#L55) [places](https://github.com/steelbrain/linter-ui-default/blob/185776716a33523359778c01c92216a5fbcbc005/lib/panel/index.js#L36) in the code where that setting gets changed, one of which forces it off, the other _does_ toggle it... but is a manual command you need to run from the Command Palette or create a keybinding for yourself.

maybe you have some other package that is modifying it?

**Comment by zaaack** [comment]
I'm pretty sure this is a bug, the config.cson will change after I toggled linter panel manually.

**Comment by keiter** [comment]
Just chiming in to say I'm also affected by this bug.

**Comment by jordanweaver** [comment]
> although I'd say that the "Show Panel" option should override it if it doesn't currently.

I agree that "Show Panel" (or some other top-level option) should provide the final say. I typically don't want to the see the panel until I'm ready to address those issues (we still get status bar hints) and currently there is no way to reliably keep it out of sight.

**Comment by djdaniels90** [comment]
Ya this is a very irritating 'feature'

**Comment by jordanweaver** [comment]
> For now, I just turned off both options settings show panel and hide panel when empty.

You'll notice this doesn't stick, as the next time you want to view the panel (e.g., clicking the Status Bar icons) the "Show Panel" option gets reselected in the package settings. As others have noted, the settings shouldn't be modified under the covers by simply using the package. If you set something, it should stay that way until you decide to change it again.

**Comment by Arcanemagus** [comment]
Looking at the comments here I'm a bit curious how people are expecting that setting to work. It sounds like you are _explicitly_ asking for the panel to show ("clicking the Status Bar icons") and then are confused as to why the setting allowing it to show has been enabled for you.

How do you want the setting to work if you don't want it to control the visibility of the panel?

**Comment by jordanweaver** [comment]
Thanks for the clarification. Just speaking for myself, I didn't think the status bar icons affected the setting but just toggled the panel temporarily for that file. But if toggling the panel is only done through via setting then this makes sense. 

When I first read the "Show Panel" option, I assumed it controlled the behavior for any new file opened. So if unchecked, I can view the panel in one file but if I open a new file with errors it will not show by default.

I realize now that I'm describing this behavior that it's probably somewhat complicated to support (managing panel state for multiple files). I will keep this in mind as I continue to use the package and see if that helps shift my workflow.

**Comment by ithuvanian** [comment]
In my experience, the problem occurred after I explicitly asked the panel
*not* to show. That is, I clicked the status bar arrow to bring it up and
then clicked the down arrow to hide it, which all worked normally. The
issue was that when I switched tabs to view a different file, the panel
would reappear even though the last command I had given was to hide the
panel. In other words, pulling up the panel changed the global settings,
but hiding the panel in one file did not change the global settings; the
panel would remain visible elsewhere. I should mention that I haven't
experienced this bug for some time, maybe someone else can clarify if it's
still happening for them.

On Dec 4, 2017 2:05 PM, "Landon Abney" <notifications@github.com> wrote:

Looking at the comments here I'm a bit curious how people are expecting
that setting to work. It sounds like you are *explicitly* asking for the
panel to show ("clicking the Status Bar icons") and then are confused as to
why the setting allowing it to show has been enabled for you.

How do you want the setting to work if you don't want it to control the
visibility of the panel?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/steelbrain/linter-ui-default/issues/379#issuecomment-349070230>,
or mute the thread

**Comment by Arcanemagus** [comment]
@jordanweaver So if I'm understanding this you want basically three levels:

* Manual trigger of the status panel that forces it showing regardless of any settings _and_ doesn't change the settings
* `Show Panel` that determines whether or not the panel will show normally at all (allows empty panel to show)
* `Hide if empty` that determines whether it will automatically show/hide if there are messages for the current filter level (line/file/project)

> I should mention that I haven't experienced this bug for some time, maybe someone else can clarify if it's still happening for them.

@ithuvanian There were some changes a while back fixing/changing the behavior which might be around when you hit this.

**Comment by jordanweaver** [comment]
@Arcanemagus: I think that sums it up nicely. Sorry if I was rambling!

**Comment by StephenReich** [comment]
i've been keeping my eye on this issue for a while now, this bug is driving me nuts! I constantly have to go back into the preferences to uncheck the "Show Panel" option. It will be fine for a while, and then after some time it will start popping up every time my linter catches something. Very annoying on a smaller laptop screen. Please investigate!

**Comment by steelbrain** [comment]
Hi @StephenReich

Can you please post your Linter config? I think you might have the bottom status icons set to toggle panel so the panel gets enabled again when you click them (you can change this behavior in settings also)

**Comment by StephenReich** [comment]
Ahah! I did not realize clicking the status bar toggled the panel from automatically displaying on lint. I was thinking it acted the same as the collapsing arrow on the linter panel. Thank you for the clarification. My apologies!

**Comment by Xiaohong-Deng** [comment]
After I upgraded Atom to 1.40.1 through [packagecloud.io/AtomEditor/atom](packagecloud.io/AtomEditor/atom) this probelm started to keep happening: no matter how I close the linter status panel, every time I reopen Atom it pops up again if it's not empty.

Turns out it is a long lasting bug?

**Comment by ssribeiro** [comment]
also affects me very very annoying. I will disable the package till solved..

**Comment by stwr667** [comment]
I don't want the Panel to ever show. Although from a recent atom update, it always pops up when there are linting errors, regardless of whether "Show Panel" configuration is turned off or on. 
![image](https://user-images.githubusercontent.com/1773072/67662541-9b781d00-f99e-11e9-93c5-fa7fe6064cfc.png)

**Comment by mlavi** [comment]
Potential related/duplicates: #487 #520

**Comment by feiooos** [comment]
I believe this is fixed in 1.8.1?
https://github.com/steelbrain/linter-ui-default/blob/master/CHANGELOG.md#181

**Comment by steelbrain** [comment]
Thanks @feiooos!

Fixed in v1.8.1
