### ISSUE TITLE
If "Show decorations" is on, Atom's folding arrows don't work correctly

### ISSUE THREAD

**Issue by alexrussell** [steelbrain/linter-ui-default#380]
Normally you can access the folding arrows by hovering over the gutter. When you do, the folding arrows come up and you can click these arrows to fold or unfold your code.

When `linter-ui-default` has the setting `Show decorations` turned on (regardless of any linting issues in the current document), hovering over the gutter still brings up the arrows, and most of them can be used as normal. However, if a text cursor is on a line with a folding arrow, then when hovering over the arrow, it is unusable. There are two slightly different behaviours here, but they all stem from a foldable line having a text cursor/selection:

- If the line is currently unfolded, the folding arrow literally hides as you go to click on it.
- If the line is currently folded, the unfold arrow stays in place (though all the others disappear), but cannot be clicked on.

See line 679 in the following capture:

![folding](https://user-images.githubusercontent.com/412784/28069816-b93f0386-6642-11e7-828a-acc05f83f551.gif)

**Comment by steelbrain** [comment]
Hi @alexrussell

Can you please report the Atom version you're on?

**Comment by alexrussell** [comment]
@steelbrain sorry, it's 1.19.0-beta3.

The issue doesn't happen in safe mode, it does happen if UI and syntax themes are both One Light, and doesn't happen if `linter` or `linter-ui-default` are disabled, or if both of those are enabled but `linter-ui-default` has this setting turned off (which led me to believe this setting is the culprit, especially as it's all about messing with the gutter decorations).

**Comment by steelbrain** [comment]
Not surprising, we've had many issues in the beta because of Atom's internal bugs, the most recent one was https://github.com/atom/atom/issues/14941

**Comment by dsandstrom** [comment]
Unfortunately, there is a regression and the cursor line gap is showing up again.  I think it's related to this issue.

https://github.com/steelbrain/linter/issues/1151
#189

**Comment by mehcode** [comment]
FWIW I haven't experienced this issue in my UI rewrite, [linter-ui-plus](https://atom.io/packages/linter-ui-plus).

**Comment by steelbrain** [comment]
Is this still an issue on the latest beta?

**Comment by alexrussell** [comment]
@steelbrain as far as I can tell it (and the cursor gutter background issue) is fixed!
