### ISSUE TITLE
Enabling linter-ui-default causes computer to crawl/lag

### ISSUE THREAD

**Issue by dmmulroy** [steelbrain/linter-ui-default#382]
I'm not sure how to debug/fix an issue I'm having.  When I enable the Linter-UI-Default package atom causes my computer to come to a crawl (taking 1 - 3 seconds to switch windows/applications).  Any ideas?

**Comment by dmmulroy** [comment]
Removing my project folders and adding them again seems to have resolved the issue.

**Comment by Arcanemagus** [comment]
Is this reproducible at all? How many `linter` messages was it trying to display?

**Comment by dmmulroy** [comment]
I have not been able to reproduce and there were no linter messages for the files I had open.
