### ISSUE TITLE
Selection highlight not showing

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/linter-ui-default#385]
Related to #359, it seems that the cursor line highlighting added in #190 is _also_ broken in Atom v1.19.0 as reported by @50Wliu.

If I go into the Dev tools and disable the `left: 0; right: 0;` on the `atom-text-editor.editor .linter-row` style (which "fixes" #359) _and_ set a `width` and `height` for the specific "cursor highlight" `<span>` then things work, but something is obviously quite broken.

@50Wliu I'm not sure that this ever got filed on Atom, and https://github.com/atom/atom/issues/14941 unfortunately doesn't seem to fix things as was earlier assumed. Should this be filed on Atom as a bug there since it has regressed in v1.19.0, or is it a bug here?

**Comment by Arcanemagus** [comment]
Note that https://github.com/atom/atom/pull/15012 will allow a _much_ simpler implementation of this once it is included in Atom.

**Comment by 50Wliu** [comment]
I have no clue who's at fault here.

**Comment by Arcanemagus** [comment]
Since this has regressed since v1.18.0 (just confirmed myself) I'm filing it on `atom/atom`, if it's something that needs to be fixed here though I'll leave this open for tracking 😉.

**Comment by 50Wliu** [comment]
This has been fixed.

**Comment by steelbrain** [comment]
Thanks @50Wliu
