### ISSUE TITLE
little bug on atom 1.18 bottom panel. That desappear when linter-ui-default disabled.

### ISSUE THREAD

**Issue by Haversham94** [steelbrain/linter-ui-default#397]
![image](https://user-images.githubusercontent.com/11727589/28773712-f7677474-75ea-11e7-8688-27a93465bfa1.png)

**Comment by steelbrain** [comment]
That is not a bug, it's the icon for Atom docks minimizing/maximizing. You'll see the same icon on the edge of Tree View as well, or right side if you use the new github package

**Comment by Haversham94** [comment]
Yeah thanks. actually i was talking about the text that showed behind the icon. some time it is just a black square and do not show up when i deactivate the linter-ui-default

**Comment by steelbrain** [comment]
It would show up if use any other package that uses bottom docks, we don't do anything in our package to show it there, just an Atom bug. @Arcanemagus will have the link

**Comment by Haversham94** [comment]
Ok thanks!

**Comment by Arcanemagus** [comment]
The bug in question is https://github.com/atom/atom/issues/14915.

@steelbrain It's actually not any usage of a bottom Dock, but any that default to hidden on Atom's launch.

@Haversham94 If it's driving you crazy there is a workaround posted as option 4 in https://github.com/atom/atom/issues/14915#issuecomment-314312281, you can add that to your Atom stylesheet.

**Comment by Haversham94** [comment]
Thank you @Arcanemagus
