### ISSUE TITLE
Tooltips that overflow into another panel get cut off

### ISSUE THREAD

**Issue by coopermaruyama** [steelbrain/linter-ui-default#404]
Here's a screenshot of what I mean:

![screenshot](https://www.dropbox.com/s/ei62qm8sabdf7oh/Screenshot%202017-08-03%2015.44.13.png?dl=1)

When the tooltip message overflows the active panel, the other panel cuts off the message. The z-index of the tooltip should be higher.

**Atom version:** 1.18.0
**OS:** OS X Sierra 10.12.5
**Machine:** MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by steelbrain** [comment]
That's an Atom theming issue, submitted a PR to themes a while back (maybe last year?), they got rejected because they wanted to explore a different way to solve it.

@Arcanemagus will have the link for you

**Comment by coopermaruyama** [comment]
Ooh, that's rough. If you can recommend a workaround/solution I'll put together a PR. Maybe measure the remaining width and ensure the tooltip width is less than that?

**Comment by Arcanemagus** [comment]
Looks like https://github.com/atom/atom/issues/11249 is the issue you were thinking of, the PR in question  is https://github.com/atom/one-dark-ui/pull/127.
