### ISSUE TITLE
Panel position doesn't persist in Dock

### ISSUE THREAD

**Issue by rtfeldman** [steelbrain/linter-ui-default#413]
I'm running Atom 1.19.0, and linter-ui-default 1.6.4 (all packages up-to-date).

I have this in my keybindings:

```coffeescript
'atom-workspace':
  'cmd-escape': 'linter-ui-default:toggle-panel'
```

Here's a gif of what I tried to do:

![fvnjjxzfzq](https://user-images.githubusercontent.com/1094080/29229379-121e8d42-7eac-11e7-84a5-01034eed29f0.gif)

1. I check "Show Panel" and the linter pane appears in a new tab.
2. I drag it to the bottom dock position.
3. I cause a linter error, and it shows up as expected.
4. I use the `cmd-escape` keybinding to try and close the panel. Nothing happens.
5. I close the panel by clicking the X.
6. I use the `cmd-escape` keybinding again. The panel reopens, but in a new tab, not at the bottom.

What I'd expect that didn't happen:

* After dragging the panel to the bottom position, from then on, when its visibility gets toggled, it is still in the bottom position.
* Using the `linter-ui-default:toggle-panel` keybinding should toggle the panel open and closed. At present, it seems it'll open it if it's closed, but will not close it again once it's open.

This used to work before the Docks change; the `cmd-escape` keybinding would toggle the panel open and closed at the bottom of the screen. It was great! That's what I'm trying to get back to. 😄

**Comment by steelbrain** [comment]
Hi @rtfeldman

In the gif, you didn't drag/drop it to a dock, but to a seperate pane container. You should hover it around the center bottom until a ribbon appears and then drop on the ribbon to have it as a dock.

Also this is unrelated to Linter as Atom handles all the dock UI but I'll try to help as much as I can.

**Comment by rtfeldman** [comment]
I was totally unaware of that distinction. Thank you so much @steelbrain! Worked like a charm. 😄
