### ISSUE TITLE
Error message overlaps autocomplete dropdown

### ISSUE THREAD

**Issue by szyablitsky** [steelbrain/linter-ui-default#415]
**Atom** 1.19.0
**OS** Ubuntu 16.04 LTS
**linter-ui-default** 1.6.4

An error message should be displayed underneath autocomplete dropdown.

![screenshot from 2017-08-13 14-35-13](https://user-images.githubusercontent.com/1945924/29246188-a6f6591a-8035-11e7-9ee9-d205f3b94730.png)

**Comment by steelbrain** [comment]
I am surprised, the last time I checked, we hid the linter tooltip whenever you add text unless you moved your cursor over to the place in which case I would call it the intended behavior.

Can you please explain how you were able to achieve this?

**Comment by rayvbr** [comment]
I experience the same problem. I first encountered it directly after upgrading to 1.19. 

As for how to reproduce it: I don't do anything specific. You edit a line that has an error in it, causing the linter tooltip to show. If the autocomplete dropdown becomes visible, it is obscured by the linter tooltip. Note that my linter-ui 'tooltip follows' setting is set to 'Both', although the problem obviously only manifests itself during keyboard edits

**Comment by szyablitsky** [comment]
@steelbrain My experience is exactly the same as @rayvbr described.

**Comment by pingshunhuangalex** [comment]
I can confirm I have similar issues. I need to wait a bit for the tooltip to disappear first.

**Comment by binaryfunt** [comment]
This occurs for me with linter-ui-default 1.6.5 and linter-jshint 3.1.5, Atom 1.19.0, Windows 10. If I start typing a line in a javascript file, it'll pop up with a missing semicolon warning over the autocomplete dropdown

**Comment by SpainTrain** [comment]
I will try to look into root cause for this, but a mitigation for those experiencing this is to add the following to `~/.atom/styles.less` (assuming you use builtin https://atom.io/packages/autocomplete-plus)

```less
atom-overlay.autocomplete-plus {
    z-index: 5 !important;
}
```

This just places the autocomplete overlay "above" the linter tooltip overlay (and possibly other overlays), so keep in mind it may obscure something you indeed want to see.  Works for my setup/habits, but caveat emptor YMMV

**Comment by billdami** [comment]
Experiencing the same issue on OSX 10.12.6, atom 1.19.2, linter 2.2.0, linter-ui-default 1.6.7, linter-eslint 8.21

**Comment by dominic-p** [comment]
I'm experiencing the same thing since upgrading to Atom 1.19 (see atom/atom#15402). My system:

Windows 10 build 1607

Atom : 1.19.2
Electron: 1.6.9
Chrome : 56.0.2924.87
Node : 7.4.0

apm 1.18.4
npm 3.10.10
node 6.9.5 ia32
python
git 2.11.1.windows.1
visual studio

**Comment by nwaywood** [comment]
@SpainTrain's fix works for me. Though ideally i think the tooltip should be hidden whenever the autocomplete dialog is shown

**Comment by rayvbr** [comment]
Unfortunately, it didn't work for me. I'm using go-plus for autocompletion

**Comment by SpainTrain** [comment]
@rayvbr bummer

You may be able to get it to work by finding the right selector for you. 

1. open dev tools in atom
1. reproduce the issue
1. find the right part of the DOM in the Elements tab
1. see if there is a usable selector for your autocomplete overlay (see screenshot)

![selection_586](https://user-images.githubusercontent.com/380032/29604057-419591e0-87b4-11e7-8291-a873112a8493.png)

LMK if any of those steps need more detail

**Comment by rayvbr** [comment]
@SpainTrain Thanks, that did the trick. It turned out that go-plus was using autocomplete-plus underwater (so the selector was correct), but that z-index of 5 was just too low. I set it to 20 and that managed to fix the issue

**Comment by steelbrain** [comment]
Was able to repro this myself today, expect fix soon!

**Comment by mifi** [comment]
Still an issue when Tooltip Follows = Both (default). No longer a problem when I set Tooltip Follows to Mouse.
