### ISSUE TITLE
tooltip only shows on exact place of error

### ISSUE THREAD

**Issue by jhoogeboom** [steelbrain/linter-ui-default#430]
I might not always know where the error is on the line, can I see the tooltip by clicking the dot?

![2017-09-02 12 13 39](https://user-images.githubusercontent.com/1828504/29994786-55af6b84-8fd8-11e7-875b-32ba0b729b72.gif)

**Comment by steelbrain** [comment]
This is actually an issue with the provider, it's providing zero width ranges. Can you please reopen this in the provider instead?
