### ISSUE TITLE
Clicking on Linter Warnings Does Nothing

### ISSUE THREAD

**Issue by mmstick** [steelbrain/linter-ui-default#433]
Using this with linter-rust, for the last few months I've noticed that the panel doesn't seem to do anything at all. Clicking on the icon for linter warnings should open a file with a warning and display the line that is being warned, as well as opening the panel to list all of the available warnings. Instead, it does nothing at all.

**Comment by Arcanemagus** [comment]
What do you have "Panel represents" set to in the settings? Maybe `linter-rust` isn't reporting the correct paths back to `linter`.

**Comment by mmstick** [comment]
It was set to **Current File**. Setting it to **Entire Project** seems to have fixed it.
