### ISSUE TITLE
Strange background artefacts in bottom panel on Ubuntu

### ISSUE THREAD

**Issue by axllent** [steelbrain/linter-ui-default#445]
When opening Atom (currently 1.20.1) there appears to be some rendering issues with linter-ui-default on bottom panel prior to opening the tab for the first time. The only way I can "get rid of" the problem is to open and close the linter tab, but this happens on every single new instance of Atom so it is annoying to say the least.

I would normally stay this is a graphics card issue, however it happens on both my desktop (NVidia GPU) as well as laptop (Intel GPU), both running Ubuntu Linux. I'm not sure if this is an Atom bug, or a linter-ui-default bug, but this is probably the place to start as I haven't experienced the issue with any other package. I have also tried starting atom with the `--disable-gpu` flag and that makes no difference.

The screen capture demonstrates what I'm seeing.

![peek 2017-09-29 09-06](https://user-images.githubusercontent.com/1463435/30988810-0890a338-a4f8-11e7-9619-5b1376513528.gif)

**Comment by Arcanemagus** [comment]
Known bug in Atom (https://github.com/atom/atom/issues/14915), see that issue for a temporary workaround or switch to the beta build of Atom as this is fixed in v1.21.0 😉.

**Comment by axllent** [comment]
Thanks for that info @Arcanemagus - I did search initially but did not find it! The work-around works ;-)
