### ISSUE TITLE
Linter well positioned but still appearing as tab

### ISSUE THREAD

**Issue by BigfootN** [steelbrain/linter-ui-default#452]
Hello,

My issue is not about positioning the linter. I have a problem as to how the linter is shown. Indeed, it always appears in a tab.

Preview:
![linter](https://i.imgur.com/RVPTnp0.png)

Here are my settings:
![Settings](https://i.imgur.com/UPCAnRH.png)

![Imgur](https://i.imgur.com/CJY2fI6.png)

Additional information:
OS: Archlinux
Atom package: [atom-editor-bin](https://aur.archlinux.org/packages/atom-editor-bin/)
Atom version: 1.21.2

Thank you in advance

**Comment by scottastrophic** [comment]
@BigfootN see if #348 resolves your issue; it did for me.

**Comment by Arcanemagus** [comment]
@BigfootN _where_ does the "Linter tab" show up? Is it in the same location as documents you are editing? Or in a separate section at the bottom of the window?

If it's the latter that's the _expected_ situation as the panel is in the bottom `Dock` of Atom.

**Comment by BigfootN** [comment]
@scottastrophic Thank you but it wasn't what I was looking for.

@Arcanemagus It's in fact the later, so from what I understand it's the expected situation ? That it appears *within* a tab ? That there is a tab opened with the title "Linter" ?

Thank you very much again in advance.

**Comment by Arcanemagus** [comment]
@BigfootN It depends on your theme how it looks, it seems yours expands it to fill the entire space, I've seen others hide it when there is only one, and still others show them as a regular (small) tab.

All of that is just how Atom handles [Docks](http://blog.atom.io/2017/05/23/docks-deep-dive.html).
