### ISSUE TITLE
Errors are difficult to see with a light syntax theme

### ISSUE THREAD

**Issue by zavarka** [steelbrain/linter-ui-default#456]
Version 1.6.10

When Atom Syntax Theme is light, linter errors in tooltips contain low contrast elements which are very difficult to read.  Please see the attached screen shot where Syntax Theme is set to "Atom Material Light".

<img width="628" alt="screen shot 2017-11-22 at 19 25 19" src="https://user-images.githubusercontent.com/8014954/33157979-05b68720-cfbb-11e7-9e68-a300306dd135.png">

Thanks.

**Comment by Arcanemagus** [comment]
The colors come from your theme:
https://github.com/steelbrain/linter-ui-default/blob/f93b38c7c34e0bbce20ddb82db282295c3ee0685/styles/linter-ui.less#L17-L19

You'll have to file an issue there as to why `@text-color` has little contrast with `@inset-panel-background-color`.
