### ISSUE TITLE
Next and previous error commands.

### ISSUE THREAD

**Issue by jordwalke** [steelbrain/linter-ui-default#46]
Many people cannot use a mouse easily and so having keyboard shortcuts (or at least the capability to create these keybindings) would be very helpful. Here's some things that would be helpful.

- Next error command (currently supported).
- Previous error command (not currently supported).
- Ability to only cycle through errors in the current file vs entire project.

**Comment by steelbrain** [comment]
Thank you for the request, I'll be implementing these as a part of #40

**Comment by jordwalke** [comment]
sounds great!

**Comment by steelbrain** [comment]
Fix is in #56

**Comment by jordwalke** [comment]
Thank you. I'll try it.
