### ISSUE TITLE
Can't permanently disable Show Panel 

### ISSUE THREAD

**Issue by CosmicTacoCat** [steelbrain/linter-ui-default#462]
I have to disable show panel each time I re-open Atom. The panel can kind of get in the way when suddenly pops in, you know?

Anyway to fix that?

**Comment by surdu** [comment]
I have the exact opposite problem: Show Panel always appears to disable itself and I have to go and re-enable it in the settings.

**Comment by rddunphy** [comment]
I had the same problem - this may be related to #379. 

It appears that when toggling the panel with the statusbar, the "Show Panel" option is toggled, but when toggling it with the arrow button at the top of the panel, it isn't. So, as long as you use only one of these, all is fine, but if you open with the statusbar and close with the arrow or vice versa, the option has changed. 

I got around this by changing the "Statusbar Click Behaviour" setting to "Toggle Status Bar Scope" to prevent myself from changing it by accident, but the default behaviour is pretty confusing. For instance, if you open the panel using the status bar, then close it with the arrow, then attempt to reopen using the status bar again, nothing happens - you need to click it again. Could the statusbar control be changed to be consistent with the behaviour of the arrow?

**Comment by SuperSandro2000** [comment]
This needs some attention as the default behavior is very unintuitive.

**Comment by vanboom** [comment]
:+1: I never use the panel as the editor features work great while I am editing.  The panel keeps coming back with focus even though show panel is not checked

**Comment by aminya** [comment]
You can disable the panel in the settings of `linter-ui-default`:
![image](https://user-images.githubusercontent.com/16418197/94526248-de6bf180-01fa-11eb-8a8a-9d14ede05b93.png)

**Comment by aminya** [comment]
This was fixed in https://github.com/steelbrain/linter-ui-default/issues/379.

@vanboom Do you get the error in the latest version?

**Comment by vanboom** [comment]
No, it appears to work perfectly now.  Thanks! :+1:
