### ISSUE TITLE
C++ some error in standalone header file. Code builds.

### ISSUE THREAD

**Issue by nardev** [steelbrain/linter-ui-default#480]
![cppproblem](https://user-images.githubusercontent.com/696054/36294270-db100ef2-12df-11e8-94c5-254b4ce40783.png)

That header is just a file for placing some default values.. the code builds but if i define String type, the linter gives an error.

Any idea?

**Comment by Arcanemagus** [comment]
Please file this on [linter-gcc](https://github.com/hebaishi/linter-gcc), this package (`linter`) is just a manager of the providers.
