### ISSUE TITLE
The new styling is horrible

### ISSUE THREAD

**Issue by stoico** [steelbrain/linter-ui-default#484]
What's the latest version with the old UI?

**Comment by Arcanemagus** [comment]
`linter@1`, however that has no support for v2 providers, of which virtually all maintained ones have moved on to.

With `linter@2` the UI was separated out into a separate package (this package), so _anyone_ can write a UI for it, you are welcome to re-implement the v1 UI using the new UI provider API.

I know of only one other UI made, which is still in an "experimental" state: [linter-ui-plus](https://atom.io/packages/linter-ui-plus).
[minimap-linter](https://atom.io/packages/minimap-linter ) also takes advantage of the UI service to get messages.
