### ISSUE TITLE
Doesnt reopen dock when hide when empty checked

### ISSUE THREAD

**Issue by pbarbiero** [steelbrain/linter-ui-default#488]
Version 1.7.0

When `hide panel when empty` is checked, the dock gets closed out when theres nothing to show. This means, when there is something to show, the dock does not automatically reopen. I have to leave the theme "hide dock toggle buttons" unchecked and manually open the dock each time. 

1.6.10 and prior works fine.

**Comment by Arcanemagus** [comment]
Looks like somebody else filed this about an hour before you did, closing as a duplicate 😉.

**Comment by Arcanemagus** [comment]
Duplicate of #487
