### ISSUE TITLE
Hover tooltip gets "stuck" when mouse moved to message box

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/linter-ui-default#51]
If the line _right_ above the message box has an error on it and you move the mouse down to the message box quite often the tooltip will show up and get "stuck" showing, since the last position the cursor was at _in the editor_ was on the line.

As the tooltip has a higher Z-order than the message box, this means the first 1-2 messages are mostly obscured.

**Comment by steelbrain** [comment]
We have two ways to solve this

1. Do not show the bubble if the thing directly below it isn't a text editor
2. Hide the bubbles behind the box

**Comment by Arcanemagus** [comment]
Personally I'd say option 2 would be better, but whicher is easier to implement will work.

Note that when this happens the tip of the "pointer" is still in the editor, it's just that the majority of the tooltip is off of the editor.

**Comment by steelbrain** [comment]
I think there's a potential fix for this in https://github.com/AtomLinter/linter-ui-default/commit/89838df612a728fef3e59dde59ad52de375651a5. Can you please try and see if it works?

**Comment by steelbrain** [comment]
Sorry for the confusion, completely misunderstood the title. I've opened PRs in the UI packages to fix this

**Comment by steelbrain** [comment]
Closing in favor of https://github.com/atom/atom/issues/11249
