### ISSUE TITLE
Option to show tooltip on top of the line instead of below.

### ISSUE THREAD

**Issue by trusktr** [steelbrain/linter-ui-default#524]
It'd be nice to have this option. It would come in handy when using `atom-typescript`, which for example shows a custom popup below the mouse position, which overlaps with the error tips:

![screen shot 2018-11-05 at 11 20 59 am](https://user-images.githubusercontent.com/297678/48022021-dd091b80-e0ee-11e8-9acf-5fc2546239e0.png)

**Comment by steelbrain** [comment]
Hi

Linter gets ranges of text to highlight within the editor from its providers, in this case `atom-typescript`. Please open an issue on the provider asking them to provide more specific ranges :)

Thanks

**Comment by trusktr** [comment]
I don't think the range is the problem (ignore the red line in the screen shot, I am hovering with my mouse directly on `yIndex`, and the tooltip appears exactly below it).

After you have the range, how do you determine where to place the tooltip? Maybe that's the part that needs to be changed to do this properly (assuming the range is correct, and it seems like it is to me).

I have an idea for a quickfix: I can set `transform: scaleY(-1); transform-origin: -0.5em` on the tooltip itself (possibly need to adjust the origin value based on trial/error or some other criteria), then set `transform: scaleY(-1)` on the tooltip content to flip it. This should in theory place the tooltip exactly above the line.

**Comment by trusktr** [comment]
Another example just for show:

<img width="1170" alt="screen shot 2018-11-10 at 2 33 27 pm" src="https://user-images.githubusercontent.com/297678/48306851-aae42900-e4f5-11e8-8928-4f673444aed8.png">

**Comment by trusktr** [comment]
Sidenote, the blue messages are missing the styling for `::before` so that it makes the little triangle, like the red one.
