### ISSUE TITLE
Sort columns is not working

### ISSUE THREAD

**Issue by wesinator** [steelbrain/linter-ui-default#532]
```
macOS
atom 1.34.0
linter 2.3.0
linter-ui-default 1.7.1
linter-pylint 2.1.1
```

Sorting by columns does not seem to work at all:
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/5124946/53432106-e4b33f80-39bf-11e9-9af2-1743a35839cf.png">
45 warnings, but clicking arrows on severity column still just shows the same first entry.

Other columns don't sort either

No console output when clicking sort arrows

**Comment by Arcanemagus** [comment]
The count in the status bar is the project wide count (by default), while the panel is only for the currently opened file (again, by default).

Are you sure those 217 messages (45 warnings + 172 info) are in the current file you had open?

**Comment by wesinator** [comment]
You are correct, that is the total count, but there are still mixed info and warnings on the current file.
Clicking sort arrows does not move the view for any of the columns, including Line number.

**Comment by Arcanemagus** [comment]
What is the output of `apm list --installed`? This is working for me locally so I'm guessing you have some other package that is breaking this.

**Comment by wesinator** [comment]
```
├── Hydrogen@2.8.0
├── atom-dns-resolver@1.3.0
├── atom-whois@0.1.0
├── busy-signal@2.0.0
├── intentions@1.1.5
├── language-batchfile@0.7.5
├── language-csv@1.1.2
├── language-har@1.0.0
├── language-powershell@5.0.0
├── language-vbscript@0.9.0
├── language-yara@3.4.0
├── linter@2.3.0
├── linter-pylint@2.1.1
├── linter-ui-default@1.7.1
├── pretty-json@2.0.3
├── sort-lines@0.18.0
└── wordcount@3.0.0
```

I think hydrogen may be the culprit.

**Comment by Arcanemagus** [comment]
Hmmm, can you try disabling `hydrogen`, restarting Atom, and seeing if that helps? I know that package intercepts mouse clicks in other areas.

**Comment by wesinator** [comment]
Hmm, disabling Hydrogen and restarting fixed it, but now it still works after re-enabling hydrogen.

**Comment by Arcanemagus** [comment]
I'll go ahead and close for now then, if you find a way to reproduce this please let us know so we can investigate and get it fixed!
