### ISSUE TITLE
linter not linting

### ISSUE THREAD

**Issue by giov3ka** [steelbrain/linter-ui-default#535]
I have the latest Atom build for Mac OSX, and installed the following packages:
linter 2.3.0
linter-ui-default 1.7.1
csslint 1.2.0

Issue 1: I open a file called master.css.  I intentionally delete a ";" from the end of the css statement.  Nothing happens.  No flags.

Issue 2 (html): I open a file called index.html.  When I delete the "<body> tag and save, nothing happens.  The settings are to show changes upon saving.

Any ideas?

Thank you!

**Comment by Arcanemagus** [comment]
The [csslint](https://github.com/tcarlsen/atom-csslint) Atom package appears to be no longer maintained... just like `csslint` itself. It never used Linter in the first place though.

If you _require_ `csslint` support in Atom you should install [linter-csslint](https://atom.io/packages/linter-csslint), but you should look into [linter-stylelint](https://atom.io/packages/linter-stylelint) as it is a _far_ better linter for style code, and is actually maintained unlike `csslint`.

In any case I'm closing this issue as it has _nothing_ to do with `linter-ui-default`.
