### ISSUE TITLE
showPanel option always resets to True on every launch

### ISSUE THREAD

**Issue by shuntaroy** [steelbrain/linter-ui-default#555]
On every launch of Atom (or reload), the option "Show Panel" is reset to True even if it is set to False before the relaunch.
I guess this started to happen in the recent update.

- To reinstall this package with deleting the corresponding config entry did not solve this issue.
- This happens even when all other linter-related plugins are disabled

**Comment by perpetualgrimace** [comment]
This has been driving me nuts.

**Comment by steelbrain** [comment]
Sorry about that, I'll investigate it this weekend

**Comment by xiinator** [comment]
Any update? This has been driving me nuts as well. Thanks!

**Comment by Foxclip** [comment]
Waiting for update as well.

**Comment by leptest** [comment]
Thanks!
