### ISSUE TITLE
[feature request] Rule tooltip

### ISSUE THREAD

**Issue by mindrones** [steelbrain/linter-ui-default#559]
When hovering a rule in a ESlint config file (`json` or `YAML`) it would be great to get a tooltip with the [rule's description](https://eslint.org/docs/rules/), to be able to get a quick reminder about it.

![linter-ui-rule-tooltip](https://user-images.githubusercontent.com/1309648/66719405-24138c80-ede7-11e9-8d2e-a212a44dbeb3.png)

Eventually, clicking on the tooltip could open the correspondent doc page in the default browser.

If used in combination with https://github.com/sharvil/api-docs, clicking on the tooltip  could open the the rule documentation in Atom itself.

<img width="963" alt="Screenshot 2019-10-13 at 18 19 34" src="https://user-images.githubusercontent.com/1309648/66719317-14e00f00-ede6-11e9-8472-bde744f7db03.png">

**Comment by steelbrain** [comment]
Linter API has support for `url` in the linting messages, it's up to the provider to provide linter with these urls tho. So maybe ask linter-eslint to supply `url`s? :)

Your request is very valid but is out of scope of this package, feel free to continue discussing
