### ISSUE TITLE
Uncaught TypeError: range.intersectsWith is not a function

### ISSUE THREAD

**Issue by quasar2007** [steelbrain/linter-ui-default#562]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 8.1 Pro
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.8.0

### Stack Trace

Uncaught TypeError: range.intersectsWith is not a function

```
At C:\Users\Kara Kartal\.atom\packages\linter-ui-default\lib\helpers.js:102

TypeError: range.intersectsWith is not a function
    at /packages/linter-ui-default/lib/helpers.js:102:53
    at Set.forEach (<anonymous>)
    at filterMessagesByRangeOrPoint (/packages/linter-ui-default/lib/helpers.js:99:12)
    at Editor.updateTooltip (/packages/linter-ui-default/lib/editor/index.js:275:22)
    at /packages/linter-ui-default/lib/editor/index.js:221:18)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-clang 0.12.1 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.36 
intentions 1.1.5 
language-ini 1.23.0 
linter 2.3.1 
linter-gcc2 0.8.7 
linter-ui-default 1.8.0 
platformio-ide 2.5.0 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
tool-bar 1.2.0 
```

**Comment by psmetcalf** [comment]
Encountered same problem,
Windows 10
Happened from using the Export Html extension

**Comment by psmetcalf** [comment]
Happened again today attempting to "Go to Declaration." Another thing to note, like OP I am using Platformio.

**Comment by Arcanemagus** [comment]
It looks like one of your providers is passing in a badly formed message that includes a "position"... but whatever "position" that is it isn't in a format that can be converted to an Atom `Range`.

Can both of you open a file you see this on and run the `Linter: Debug` command?

**Comment by aminya** [comment]
Closing in favor of another duplicate issue.  https://github.com/steelbrain/linter-ui-default/issues/576
