### ISSUE TITLE
Lint warnings not showing on Linter 2.3.1 OS X Catalina Atom 1.41.0

### ISSUE THREAD

**Issue by joscabmar** [steelbrain/linter-ui-default#565]
Despite there are some warnings, I can't get the UI to list them. Here you can see there are 4 warnings, but they are not shown:
![Screen Shot 2019-12-12 at 17 43 58](https://user-images.githubusercontent.com/6691911/70731466-05f2db80-1d07-11ea-8ed9-566f0ae54585.png)
Then when I make a mistake on purpose, It shows the error:
![Screen Shot 2019-12-12 at 17 39 36](https://user-images.githubusercontent.com/6691911/70731150-8533df80-1d06-11ea-9f29-3eb3fe2cec72.png)
I tried with linter-ui-plus and it shows them (but the package is experimental and it does not work when clicking on the warnings)
I attached the Linter Debug Info for troubleshooting. But I copy them here:
```
Platform: darwin
Atom Version: 1.41.0
Linter Version: 2.3.1
Opened file is ignored: No
Matching Linter Providers: 
  - Ansible-Lint
Disabled Linter Providers: 
Standard Linter Providers: 
  - Ansible-Lint
  - dockerlint
  - Pylint
Indie Linter Providers: 
  - Python (pyls)
UI Providers: 
  - Linter
Ignore Glob: **/*.min.{js,css}
VCS Ignored Paths are excluded: true
Current File Scopes: 
  - *
  - source.ansible-advanced
  - meta.flow-sequence.ansible-advanced
  - punctuation.definition.sequence.end.ansible-advanced
```

I am eager to help you in whatever you need to troubleshoot the issue. Thanks a lot!

**Comment by Arcanemagus** [comment]
By default the panel only shows messages for the current file, while the status bar shows the totals for the project. You can change this in the settings.

My guess is that provider is providing messages for a file other than the one that is open currently, is that the case?

**Comment by joscabmar** [comment]
Hi @Arcanemagus. Thanks for your quick response! I only had that file opened. And the moment that I added the typo, I got the panel showing the error and the status bar does not show the 4 warnings anymore. So it is definitely referring to the file. And it is like it is partially working: errors are shown, but not the warnings

**Comment by Arcanemagus** [comment]
> I only had that file opened.

There are at least [two](https://github.com/mschuchard/linter-ansible-linting/blob/188b9123fa3daf75be0d91e1686f941ec3d27e7f/lib/main.js#L220-L229) [cases](https://github.com/mschuchard/linter-ansible-linting/blob/188b9123fa3daf75be0d91e1686f941ec3d27e7f/lib/main.js#L162-L171) where `linter-ansible-linting` could return matches for a file other than the one that is currently open. If you go into `linter-ui-default`'s settings and change "Panel represents" to `Entire Project` I'm sure that those missing warnings will show up 😉.

**Comment by joscabmar** [comment]
Yes, you are right. There are
