### ISSUE TITLE
Github-releasing tagged releases

### ISSUE THREAD

**Issue by ferdnyc** [steelbrain/linter-ui-default#597]
Not so much an issue with the Atom package itself, more a Github repo housekeeping request: I noticed that the 2.1.1 release is still listed as "Latest" [by Github](https://github.com/steelbrain/linter-ui-default/releases), with the three subsequent releases just being shown as "newer tags".

Any chance we could get `v2.1.4` set as the Latest Release, from a Github perspective? Thx.

**Comment by aminya** [comment]
Thanks for opening the issue. I have a PR open that is awaiting a change from @steelbrain.
https://github.com/steelbrain/linter-ui-default/pull/588

That will automate our builds and keep both places in sync.

For now, I will do it manually.
