### ISSUE TITLE
Extra ' in gutter highlight position title

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/linter-ui-default#61]
There is an extra `'` at the beginning of the title for the `Position of Gutter Highlights` option.

**Comment by steelbrain** [comment]
Already fixed in master by https://github.com/steelbrain/linter-ui-default/commit/d5a79e22070c5e5e613e650c493a3ddadec60f94

**Comment by Arcanemagus** [comment]
Wrong config option :stuck_out_tongue:

This is still a bug in [current master](https://github.com/steelbrain/linter-ui-default/blob/6260f730605422cc07e39716dd407dda0baae3e5/package.json#L84).

**Comment by steelbrain** [comment]
Oh, sorry :stuck_out_tongue:
