### ISSUE TITLE
File outside VCS shows no errors

### ISSUE THREAD

**Issue by aklaver** [steelbrain/linter-ui-default#621]
Atom 1.54.0
linter 3.3.0
linter-ui-default v3.1.0
linter-pycodestyle 2.1.3

If I work on a Python file that is not in a VCS directory then the linter does not display errors even if they exist. If I move that file into a VCS controlled directory then they are displayed. Am I missing a setting somewhere?

**Comment by aminya** [comment]
@utkarshgupta137 Is this related to your PR?

**Comment by utkarshgupta137** [comment]
Unable to reproduce this.
@aklaver Can you share the output of `Linter: Debug`?

**Comment by aklaver** [comment]
You are going to have to step me through how to do that?

**Comment by utkarshgupta137** [comment]
1. Atom -> Menu Bar -> View -> Toggle Command Palette
2. Type/Execute `Linter: Debug`
3. Copy the output of the notification here

Also, can you reproduce this issue with any other files?

**Comment by aklaver** [comment]
Linter: Debug output:

Platform: linux
Atom Version: 1.54.0
Linter Version: 3.3.0
Opened file is ignored: Yes
Matching Linter Providers: 
Disabled Linter Providers: 
Standard Linter Providers: 
  - pycodestyle
Indie Linter Providers: 
UI Providers: 
  - Linter
Ignore Glob: **/*.min.{js,css}
VCS Ignored Paths are excluded: true
Current File Scopes: 
  - *
  - text.plain
  - meta.paragraph.text

Yes  the issue occurs with other files. If they are in VCS ignored directories then the linter does not work.

**Comment by utkarshgupta137** [comment]
> If I work on a Python file that is not in a VCS directory then the linter does not display errors even if they exist. If I move that file into a VCS controlled directory then they are displayed. Am I missing a setting somewhere?

> Yes the issue occurs with other files. If they are in VCS ignored directories then the linter does not work.

These 2 are conflicting...

Also, can you see if your issue is resolved if you disable Atom -> Settings -> Core -> Exclude VCS Ignored Paths.

**Comment by aklaver** [comment]
To be more specific, if a file is in a directory that is specified in an *ignore pattern of a VCS then it is not seen by the linter.  At any rate changing the setting for Exclude VCS Ignored Paths worked. Thanks.

**Comment by utkarshgupta137** [comment]
That is by design. Linter respects `Exclude VCS Ignored Paths` of Atom just like many other core and community packages do.

**Comment by aminya** [comment]
Thank you for the help! Appreciated
