### ISSUE TITLE
can not open linter info 

### ISSUE THREAD

**Issue by qtwrk** [steelbrain/linter-ui-default#623]
https://i.imgur.com/bz3PELu.png

when I click that , it used to be show up more detail info on older version  , then today I updated all Atom package to latest and it breaks ,give same error as https://github.com/steelbrain/linter-ui-default/issues/617

then I did uninstall and reinstall linter , ui , and linter-shellcheck   , and seems broken.

any help will be appreciated.

**Comment by aminya** [comment]
If it gives the same error as #617, it means you are using an ancient version of Atom.

**Comment by qtwrk** [comment]
oh yes, thanks ,  update atom fixed the issue  ,  thanks again !
