### ISSUE TITLE
Markdown rendering in expanded descriptions

### ISSUE THREAD

**Issue by fralps** [steelbrain/linter-ui-default#624]
Hi guys ! 

I have the latest version of Atom (1.54.0) and the last version of linter-ui-default (3.1.1) but when I click on the dropdown on one of my ruby warnings, the tags are not interpreted and the description look like this :

<img width="634" alt="Capture d’écran 2021-02-04 à 09 11 50" src="https://user-images.githubusercontent.com/48285890/106863915-7ad26300-66c9-11eb-851f-2dfb6f53132a.png">

Do you have any idea ?
Thanks 🙏

**Comment by aminya** [comment]
Could you given an example for the code, and also give the output of `Linter: Debug` command (CTRL+SHIT+P + Linter: Debug)?

**Comment by fralps** [comment]
Example of code::
-

<img width="805" alt="Capture d’écran 2021-02-04 à 09 30 48" src="https://user-images.githubusercontent.com/48285890/106865625-ba9a4a00-66cb-11eb-893e-ff14caf57552.png">

Linter: Debug:
-

<img width="459" alt="Capture d’écran 2021-02-04 à 09 30 15" src="https://user-images.githubusercontent.com/48285890/106865685-cc7bed00-66cb-11eb-95fe-6b2895407708.png">

**Comment by aminya** [comment]
Where is the problem? What do you mean by `the tags are not interpreted`

**Comment by aminya** [comment]
Oh, do you mean the rendering of the description? which has raw `<pre>` instead of markdown?

**Comment by aminya** [comment]
We should use atom-ide-base atom-ide-markdown-service to fix this issue.

**Comment by fralps** [comment]
Hum.. I still have the same issue.. 🤔

**Comment by aminya** [comment]
I haven't fixed the issue yet. 😄 I will let you know once fixed.

**Comment by aminya** [comment]
@fralps This is now fixed. I will add syntax highlighting later to make it colorful 🌈

**Comment by fralps** [comment]
Awesome ! 🤩 
Thanks 🙏
