### ISSUE TITLE
Uncaught TypeError: Illegal invocation

### ISSUE THREAD

**Issue by eoiles** [steelbrain/linter-ui-default#628]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 3.2.2

### Stack Trace

Uncaught TypeError: Illegal invocation

```
At C:\Users\stary\.atom\packages\linter-ui-default\dist\index.js:1

TypeError: Illegal invocation
    at HTMLDocument.mt (/packages/linter-ui-default/dist/index.js:1:23791)
```

### Commands

```
     -2:04.9.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:02.6.0 omnisharp-atom:settings (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  3x -1:25.8.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:22.7.0 go-to-line:toggle (atom-text-editor.editor.is-focused)
     -1:20.4.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -1:17.7.0 editor:newline (input.hidden-input)
     -0:32 pane:split-up-and-copy-active-item (a.)
     -0:20.4.0 omnisharp-atom:settings (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:11.6.0 omnisharp-atom:solution-status (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-json-format 0.2.0 
busy-signal 2.0.1 
ide-csharp 0.6.2 
ide-json 0.2.1 
ide-python 1.7.3 
intentions 1.1.5 
language-scheme 1.4.0 
linter 3.3.0 
linter-ui-default 3.2.2 
omnisharp-atom 0.31.2 
scheme-syntax 0.4.0 
script 3.29.3 
```

**Comment by aminya** [comment]
When does this happen?

**Comment by eoiles** [comment]
> When does this happen?

I just added omnisharp in my atom, then it asked me to install linter, then i click yes , then it asked me to install linter-ui-default, then i clicked yes. after every thing installed , the flame button on the bottom left is still grey, not green as it should be. then i clicked that button, so this error threw out.

**Comment by aminya** [comment]
It never supposed to be green. Gray means there are no errors. If you have errors, it becomes red or yellow.
![image](https://user-images.githubusercontent.com/16418197/107109545-000f6200-6807-11eb-8c3f-8a3c01fe56e7.png)

I will try to reproduce this.

**Comment by aminya** [comment]
atom-omnisharpt is faulty. Please use ide-csharp instead.

https://github.com/OmniSharp/omnisharp-atom/issues/1037

**Comment by eoiles** [comment]
> It never supposed to be green. Gray means there are no errors. If you have errors, it becomes red or yellow.
> ![image](https://user-images.githubusercontent.com/16418197/107109545-000f6200-6807-11eb-8c3f-8a3c01fe56e7.png)
> 
> I will try to reproduce this.

Sorry, i mean the omnisharp flame button , in it's documents it says "To use
Open a c# file

or open a scriptcs file

When the flame icon in the bottom left corner turns green, the server has started!"

**Comment by aminya** [comment]
You should use ide-csharp instead:
https://atom.io/packages/ide-csharp

**Comment by eoiles** [comment]
> atom-omnisharpt is faulty. Please use ide-csharp instead.
> 
> [OmniSharp/omnisharp-atom#1037](https://github.com/OmniSharp/omnisharp-atom/issues/1037)

so i install atom-ide , ide-csharp, linter, linter-ui-default these 4 plugins?

**Comment by aminya** [comment]
`atom-ide-base` and `ide-csharp`

Do not use the deprecated packages like `ide-ui` or `atom-omnisharp`

**Comment by eoiles** [comment]
> `atom-ide-base` and `ide-csharp`
> 
> Do not use the deprecated packages like `ide-ui` or `atom-omnisharp`

i have uninstalled ide-ui and atom-omnisharp and installed atom-ide-base ide-csharp and all of the dependicies.
but the linter won't prompt any error , and the outline didn't show anything. format code isn't working
looks like nothing is working and there is no error reported by atom. do i need something else?

**Comment by eoiles** [comment]
> 't workin
all of the enabled non-core packages are :
atom-ide-base
atom-ide-datatip
atom-ide-definitions
aton-ide-hyperclick
atom-idemarkdown-service
atom-ide-outline
atom-ide-signiture-help
busy-signal
ide-csharp
linter
linter-ui-default

**Comment by aminya** [comment]
Maybe you should open an issue in https://github.com/atom/ide-csharp?

**Comment by aminya** [comment]
From the issues, it seems that its dependencies are out of date. So could you try to update the package.json in `.atom/packages/ide-csharp`


```json
  "dependencies": {
    "atom-languageclient": "^1",
    "omnisharp-client": "^7"
  },
```
and run `apm install` in the `.atom/paclages/ide-csharp` root?


Sorry that you should do this manually. We are preparing a public issue to transfer the ide packages to the community so they can keep them up to date.

**Comment by eoiles** [comment]
> From the issues, it seems that its dependencies are out of date. So could you try to update the package.json in `.atom/packages/ide-csharp`
> 
> ```json
>   "dependencies": {
>     "atom-languageclient": "^1",
>     "omnisharp-client": "^7"
>   },
> ```
> 
> and run `apm install` in the `.atom/paclages/ide-csharp` root?
> 
> Sorry that you should do this manually. We are preparing a public issue to transfer the ide packages to the community so they can keep them up to date.

i did that .  the file was originally 
    "atom-languageclient": "^0.8.3",
    "omnisharp-client": "^7.2.2"
and i changed to 
    "atom-languageclient": "^1",
    "omnisharp-client": "^7"
then i run the command : 
C:\Users\stary\.atom\packages\ide-csharp> apm install
Installing modules done

after that,  i start the atom again, but looks like no change, nothing is working. 

I have uninstalled all the non-core packages.
so all the non-packages list is
atom-ide-base
atom-ide-datatip
atom-ide-definitions
aton-ide-hyperclick
atom-idemarkdown-service
atom-ide-outline
atom-ide-signiture-help
busy-signal
ide-csharp
linter
linter-ui-default
intentions

the intentions packages is disabled after launching atom . i enabled it and launched atom again. still disabled

**Comment by eoiles** [comment]
> > From the issues, it seems that its dependencies are out of date. So could you try to update the package.json in `.atom/packages/ide-csharp`
> > ```json
> >   "dependencies": {
> >     "atom-languageclient": "^1",
> >     "omnisharp-client": "^7"
> >   },
> > ```
> > 
> > 
> > and run `apm install` in the `.atom/paclages/ide-csharp` root?
> > Sorry that you should do this manually. We are preparing a public issue to transfer the ide packages to the community so they can keep them up to date.
> 
> i did that . the file was originally
> "atom-languageclient": "^0.8.3",
> "omnisharp-client": "^7.2.2"
> and i changed to
> "atom-languageclient": "^1",
> "omnisharp-client": "^7"
> then i run the command :
> C:\Users\stary.atom\packages\ide-csharp> apm install
> Installing modules done
> 
> after that, i start the atom again, but looks like no change, nothing is working.
> 
> I have uninstalled all the unrelated non-core packages.
> so all the non-packages list is
> atom-ide-base
> atom-ide-datatip
> atom-ide-definitions
> aton-ide-hyperclick
> atom-idemarkdown-service
> atom-ide-outline
> atom-ide-signiture-help
> busy-signal
> ide-csharp
> linter
> linter-ui-default
> intentions
> 
> the intentions packages is disabled after launching atom . i enabled it and launched atom again. still disabled
> my atom version is 1.54.0

i have reset my atom to Factory Defaults by doing
rename .atom .atom-backup

then i install 2 packages and all their dependencies.
after that the atom prompts

linter-ui-default needs to install dependencies
intentions
Install dependency?
i clicked yes. but it is not actually downloading.
so i searched this intentions package and downloaded it.
then i closed the atom and go to C:\Users\stary\.atom\packages\ide-csharp\package.json and changed to
    "atom-languageclient": "^1",
    "omnisharp-client": "^7"
again.
run C:\Users\stary\.atom\packages\ide-csharp> apm install
Installing modules done
again.
then i start the atom opened a file c.cs which content is:

namespace HelloWorld
{
    class Hello {
        static void Main(string[] args)
        {
            System.Console.WriteLine("Hello World!");
}}}}
1
2;.'.'2+3fwe
213}}}

still, no error or warning, no outlines, nothing is working.
i checked the package list again:

atom-ide-base
atom-ide-datatip
atom-ide-definitions
aton-ide-hyperclick
atom-idemarkdown-service
atom-ide-outline
atom-ide-signiture-help
busy-signal
ide-csharp
linter
linter-ui-default
intentions

the intentions is still disables.

**Comment by aminya** [comment]
Let me ask in the community group if there is any C# developer that can help you.
