### ISSUE TITLE
Hide tooltip if cursor not on the line

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/linter-ui-default#63]
It seems that the editor may be only reporting the last position of the cursor _on the content_, if you have an error on the last line of a file, and move the cursor below that the tooltip continues to show.

So for a one line file that has a message on it, moving the cursor below line one would still show the tooltip.

![image](https://cloud.githubusercontent.com/assets/427137/14034048/ad313234-f1dc-11e5-821b-538f343b1a2b.png)

**Comment by steelbrain** [comment]
It's kind-of an Atom API limitation, but you're right, we should fix it

**Comment by steelbrain** [comment]
Turns out there's no easy way to workaround this without copy/pasting a lot of non guaranteed code from core. Going to open an issue in Atom about it

**Comment by steelbrain** [comment]
Blocked on https://github.com/atom/atom/issues/11285
