### ISSUE TITLE
Please stop releasing so frequently

### ISSUE THREAD

**Issue by srevenant** [steelbrain/linter-ui-default#631]
I know this may seem counter-intuitive, but please don't release to at least the atom plugins visibility so frequently.

I absolutely love the dedication to work, but having me restart my editor nearly daily is getting annoying (I'm about ready to remove the plugin frankly) - please bunker up the work into waves so the impact isn't so great to everybody using it?  Maybe weekly?

**Comment by aminya** [comment]
Thanks for the comment. See this issue for more information:
https://github.com/steelbrain/linter/issues/1725#issuecomment-774889924

**Comment by aminya** [comment]
For your information, I am adding an explicit button to the update notification that allows skipping restarting of Atom after updating.
https://github.com/atom/settings-view/pull/1175/files

I will also check to see if it is easy to add an option to the package updater which allows setting a weekly time interval for the updates.

@srevenant
