### ISSUE TITLE
Missing Fix button and Linter UI Default: Apply All Solutions not working

### ISSUE THREAD

**Issue by PJRO** [steelbrain/linter-ui-default#632]
I am trying to use `linter-phpcs` and overall it looks to be working. The only issue is the Fix button doesn't appear in the tooltips and trying to run `Linter UI Default: Apply All Solutions` from the command pallete also doesn't do anything.

I am using Atom 1.54.0 on Windows 10.

To be sure that the issue wasn't being caused by another package, I've disabled everything unrelated, but I get the same results.
As it stands these are the only community packages I have enabled:
![image](https://user-images.githubusercontent.com/32671047/107624636-15dfb580-6c53-11eb-8aa2-3873253fcc25.png)

I've also installed another linter package, `linter-csslint` to see if the buttons appear there and they don't, which is why I thought this could potentially be this package causing me issues and not one of the language packages.

Here is a screenshot of what I see, the errors show fine both in the gutter and the linter log, there's just no way of automatically fixing them.
![image](https://user-images.githubusercontent.com/32671047/107624330-9c47c780-6c52-11eb-8365-f27fd2d4d2eb.png)

I have taken a look at the dev console in atom and there aren't any errors showing, I've also searched the issues for _fix button_ and can't find anything related.

Any help would be appreciated, from what I can tell I've installed all of the dependancies it asked for, but this may likely be down to user error, so apologies if it is!

**Comment by aminya** [comment]
Are you sure that the provider supplies fixes? 

Here is an example with atom-ide-javascript:
![image](https://user-images.githubusercontent.com/16418197/107626498-8078fd00-6c23-11eb-9d5f-915140cb0771.png)

**Comment by PJRO** [comment]
I'm honestly not sure. Is there a way to check this in their source code? anything I could search for such as a config setting that linter uses?

I'm in the middle of trying to install `atom-ide-javascript` so that I can try and replicate your example, but it's taking a while! I will reply once I've got it working

**Comment by PJRO** [comment]
I wasn't able to get the same example working as you, for some reason it doesn't flag your example as a warning (Could be down to other linters you have installed? I don't know).

But i did try to make my own example and I still couldn't see a fix button.
![image](https://user-images.githubusercontent.com/32671047/107630329-3f044400-6c5b-11eb-8507-0e66afa0be92.png)

Packages installed:

- atom-ide-base@2.3.2
- atom-ide-datatip@0.23.3
- atom-ide-definitions@0.4.1
- atom-ide-hyperclick@1.0.9
- atom-ide-javascript@1.5.0
- atom-ide-markdown-service@2.0.0
- atom-ide-outline@1.17.0
- atom-ide-signature-help@0.15.2
- atom-typescript@14.1.2
- autocomplete-paths@2.12.18
- busy-signal@2.0.1
- intentions@1.1.5
- javascript-drag-import@0.1.13
- linter@3.3.0
- linter-csslint@2.0.6
- linter-phpcs@1.7.6
- linter-ui-default@3.2.4

**Comment by PJRO** [comment]
I managed to set up Eslinter without the atom-ide packages, for some reason enabling `atom-ide-base` disabled `intentions` automatically.

After testing eslint, the fix buttons do appear, so it must be related to the `linter-phpcs` package I am using.

Apologies for wasting your time.

**Comment by aminya** [comment]
No problem. intentions packages is not actually needed.

The issue is `linter-phpcs`. Open an issue there
