### ISSUE TITLE
linter-ui-default

### ISSUE THREAD

**Issue by abubakr01** [steelbrain/linter-ui-default#661]
Cannot find module 'C:\Users\Nuga_\.atom\packages\linter-ui-default\node_modules\atom-package-deps\lib\index.js'. Please verify that the package.json has a valid "main" entry

**Comment by abubakr01** [comment]
Cannot find module 'C:\Users\Nuga_\.atom\packages\linter-ui-default\node_modules\atom-package-deps\lib\index.js'. Please verify that the package.json has a valid "main" entry

**Comment by aminya** [comment]
Reinstall.
```
apm uninstall linter-ui-default
apm install linter-ui-default
```
