### ISSUE TITLE
A new untitled document inherits all linting messages in the project

### ISSUE THREAD

**Issue by savetheclocktower** [steelbrain/linter-ui-default#667]
Let's say I've got a file open with some linter annotations.

<img width="604" alt="Screen Shot 2023-01-31 at 11 34 02 AM" src="https://user-images.githubusercontent.com/3450/215864337-86272377-46fd-40d5-8c9e-42e16fd15092.png">

If I do Cmd-N from here, I get a new untitled file and an empty text editor… but it's already got a gutter marker.

<img width="539" alt="Screen Shot 2023-01-31 at 11 35 15 AM" src="https://user-images.githubusercontent.com/3450/215864499-7339603f-a79d-4b22-bee0-7148500e0bdb.png">

And at least one display marker for the text.

<img width="645" alt="Screen Shot 2023-01-31 at 11 35 21 AM" src="https://user-images.githubusercontent.com/3450/215864575-4a6600a9-161d-4400-8477-8fc544fd41e6.png">

I've tracked down the culprit. The `filterMessages` function [will not filter out any messages](https://github.com/steelbrain/linter-ui-default/blob/5ca56747386e56e4964ff3de7acc3fc497692bf3/lib/helpers.ts#L69) if `TextEditor#getPath()` returns `undefined`, as it does for a brand-new file. So the new file inherits all the messages that were present in the original file. The markers, having been asked to mark invalid ranges, instead all mark from (0, 0) to (0, 0). The marker range grows as the user types.

This issue was introduced in [this commit](https://github.com/steelbrain/linter-ui-default/commit/e73155ade19105f8a5f0b789d4af4472cff64cf3), in which an explicit `null` check was changed to a “falsy” check.

If this line was changed because of an oversight, then the fix is a one-liner. If this line was changed on purpose, and there is some other reason why it can't be reverted to the original `null` check, then the fix is not straightforward. @aminya, if you happen to remember, please let me know. If I don't hear otherwise I'll probably contribute the simple fix in a few days.

(I am aware that Atom has been discontinued, but I continue to use this package via [Pulsar](https://github.com/pulsar-edit/pulsar). They've reverse-engineered the package repository, so I think that publishing a new version of this package for Pulsar users would be pretty straightforward.)

**Comment by savetheclocktower** [comment]
If anyone else is affected by this bug and has found this issue: adding this to my `init.js` has solved it well enough for now.

```js
atom.workspace.observeTextEditors(textEditor => {
  // Only occurs with new (untitled) documents.
  if (textEditor.getPath() !== undefined) { return; }
  setTimeout(() => {
    let decorations = textEditor.getDecorations();
    let toBeDeleted = decorations.filter(d => {
      if (d.properties.gutterName === 'linter-ui-default') { return true; }
      if (d.properties.class.includes('linter')) { return true; }
      return false;
    });
    for (let d of toBeDeleted) {
      d.destroy();
    }
  }, 50);
});
```

**Comment by vegajdr** [comment]
@savetheclocktower Thank you for the quick fix, works great for me, hopefully changing the one line will be sufficient

**Comment by asiloisad** [comment]
@savetheclocktower thank you for the temporary fix, but I hope the fix will published at pulsar package repository

**Comment by aminya** [comment]
PRs are welcome

**Comment by asiloisad** [comment]
https://github.com/steelbrain/linter-ui-default/pull/666
