### ISSUE TITLE
Update dependencies (enable GreenKeeper?)

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/linter-ui-default#67]
It looks like currently you have `babel-eslint` stuck on `^5.0.0` when v6.0.0 has been released, probably tied to that `eslint` is pinned to `~2.2.0`, which is causing a issue with `peerDependencies` in `eslint-config-airbnb@6.2.0` (which is being installed automatically by `@^6.1.0`).

It might be simplest to just enable GreenKeeper here so issues like this get caught as they happen.

**Comment by steelbrain** [comment]
Just enabled greenkeeper, see #68
