### ISSUE TITLE
Setting for font/font size

### ISSUE THREAD

**Issue by andjd** [steelbrain/linter-ui-default#69]
Hi all,

Is there a way to change the font and/or font size of the linter ui?  I don't see any way to set the settings for this in either the linter preferences or this package.  

The default is small and hard to read on my high-res monitor.

**Comment by steelbrain** [comment]
I also have a high res monitor and it works well for me, can you please share your themes and a screenshot?

**Comment by steelbrain** [comment]
Closing as no more info has been provided for over a month
