### ISSUE TITLE
allow highlighting and copying from the lint popups

### ISSUE THREAD

**Issue by oli-obk** [steelbrain/linter-ui-default#78]
Users like to copy paste error messages to google to find aid. It would be great if there were one or many of the following options:

1. a small button for copying the message to the clipboard (like on github with the repository urls)
2. text can be highlighted and copied in the messages
3. a button that goes straight to your browser and searches for the text (my least favorite option, since users will want to configure it)

**Comment by Arcanemagus** [comment]
2 is already possible btw.

**Comment by oli-obk** [comment]
Not from the popup messages, just from the message list at the bottom

**Comment by Arcanemagus** [comment]
Ah, your description seems to only apply to the message window, missed that you were talking about the pop ups in the title.

How do you envision buttons on popups working? :confused:

**Comment by oli-obk** [comment]
I don't know if it's technically possible, but I assumed that one can insert arbitrary html, so there could be an icon that when clicked puts the text into the clipboard. There could be one icon per message in case of traces. Optically it could be either before or after the text

**Comment by Arcanemagus** [comment]
Well yes, but right now the popup is hidden as soon as the mouse moves off of the line containing the message. Introducing interactable elements on the popup is going to turn detection of when to dispose of the popup into a nightmare :confused:.

* Do you wait an extra long time between when the cursor moves off the line to give the user time to get the cursor on the popup?
* Do you force the user to only get into the popup by "tracing" along the small arrow?
* How do you detect that the cursor is on the popup?
* Do you provide an option to hide all that for users (like me) who don't want any of that on the popup?
* How do you handle layout when the popup doesn't have enough room for the ideal layout?
* What if the popup is covering something besides the TextEditor? How does that change all of the above?

Those are just a few of the concerns with putting any interactive elements in the popup, even putting a button in the message list isn't ideal as you can already copy it with your cursor, but I can see having a tiny button (icon?) there for some users.

**Comment by oli-obk** [comment]
> Well yes, but right now the popup is hidden as soon as the mouse moves off of the line containing the message. Introducing interactable elements on the popup is going to turn detection of when to dispose of the popup into a nightmare

On my machine (linux), the popup is permanent until i move the text-cursor in the text-buffer somewhere else. I thought that was the expected behaviour (and I like it this way). The mouse-cursor has no influence on the popup.

> Those are just a few of the concerns with putting any interactive elements in the popup, even putting a button in the message list isn't ideal as you can already copy it with your cursor

That I consider secondary. Since as you said, you can already select and copy it.

**Comment by Arcanemagus** [comment]
Are you using the `master` branch of linter, and have manually linked in the `master` branch of linter-ui-default? That sounds like the behavior of the currently released linter and not the UI presented by this package.

**Comment by oli-obk** [comment]
I'm using the currently released linter. With the new behaviour this obviously becomes a nightmare. I'll have to check how that behaves. Because I'm already producing multi-line lints that need to be expanded by clicking the small expand icon: ![img](https://cloud.githubusercontent.com/assets/332036/15097688/ddfc170c-1523-11e6-8394-d24a79d125ea.png)

I'll get back to you once I get the master branches to work

**Comment by oli-obk** [comment]
Ok, I tried out the master branch, and it's really trippy. If I move the mouse along the highlighted text, the bubble moves with the mouse (not smooth, jumping, feels like half a second). Even if the mouse moves within the same character, the bubble refreshes.

Would you mind terribly if I added an option to reinstate the previous behavior?

**Comment by oli-obk** [comment]
side-note: traces are only really useful if the mouse can move into the bubble and click the `at line X col Y in FILENAME`

**Comment by steelbrain** [comment]
Side Note: Currently we are debouncing the activation of the tooltip to allow the user to move the cursor into the tooltip so they can click on the links in messages

**Comment by oli-obk** [comment]
> Currently we are debouncing the activation of the tooltip to allow the user to move the cursor into the tooltip so they can click on the links in messages

Thanks! I tried it out, and it's great to use.
