### ISSUE TITLE
I'm having trouble using this extension

### ISSUE THREAD

**Issue by alexbooker** [steelbrain/linter-ui-default#90]
I don't use [hub](https://github.com/github/hub) so to install the extension, I closed Atom and ran:
```
apm uninstall linter linter-ui-default

cd ~/.atom/packages
git clone https://github.com/steelbrain/linter-ui-default
cd linter-ui-default
apm install
cd ~/.atom/packages
git clone https://github.com/steelbrain/linter
cd linter
apm install
```

When I opened my project that uses [Flow](http://flowtype.org/) nothing **different** happened.

The extensions _are_ installed:

![](http://i.imgur.com/5BwJUv6.png)

I am installing this extension based on @steelbrain's comment [here](https://github.com/AtomLinter/linter-flow/issues/92#issuecomment-220567779). I want some kind of indication that Flow is being initialized.

**Comment by steelbrain** [comment]
Which package are you using? Install `flow-ide` and you'll have a spinner in the status bar that will spin every time you lint a file which has flow for it

**Comment by alexbooker** [comment]
@steelbrain I'm using `linter-flow`.  The [comment](https://github.com/AtomLinter/linter-flow/issues/92#issuecomment-220567779) of yours I referred to was for the `linter-flow` extension. Do I have to use `flow-ide`? I think I prefer `linter-flow`.

**Comment by alexbooker** [comment]
Even with `flow-ide` nothing happens :cry:

**Comment by alexbooker** [comment]
Many thanks for your response.

I'm using **`linter-flow`** but I tried **`flow-ide`** and it doesn't work either :worried: 

Must I use **`flow-ide`**? I like **`linter-flow`** because it doesn't require me to save the file before linting it.

**Comment by steelbrain** [comment]
Can you share a full page screenshot of the editor when editing a file?

**Comment by alexbooker** [comment]
Sure:

![](http://i.imgur.com/8Jwsqpy.png)

In that screenshot I had just pressed _"Save"_ and the screenshot would look the same had I just opened Atom.

**Comment by steelbrain** [comment]
By the looks in that screenshot, have you disabled the `busy-signal` package?

**Comment by alexbooker** [comment]
I installed **`busy-signal`** and now it works :tada: 

Thing is, there is no mention of **`busy-signal`** in the [instructions](https://github.com/steelbrain/linter-ui-default#installation). `apm install` didn't install it either :confused:
