### ISSUE TITLE
No cursor indication for resize handle on linter message pane

### ISSUE THREAD

**Issue by thehans** [steelbrain/linter-ui-default#91]
When hovering over the top edge of the messages pane, I would expect the cursor to change to a "resize arrow" to indicate that I can click drag to resize.

Currently the mouse cursor does change to this arrow, but only after mousedown. I spent some time hovering my mouse all around to try to figure out how to resize it since I saw no indication when I was in the right spot.

Also, not sure if this is related to Issue #14 , I'm able to resize, its just difficult to see where the handle is.

Atom 1.7.4, 
linter 1.11.4
UI Theme: Atom Dark, Syntax Theme: Atom Dark

**Comment by steelbrain** [comment]
Can you add a screenshot to demonstrate what you are saying?

**Comment by Arcanemagus** [comment]
The cursor should change to the [`ns-resize`](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) cursor when the mouse is in a position that allows resizing the panel if a click-and-drag is performed.

**Comment by Arcanemagus** [comment]
Or maybe even the `row-resize` cursor?

**Comment by steelbrain** [comment]
I don't think resizing is implemented in this package at all right now, I'll keep this in mind when doing it though

**Comment by thehans** [comment]
I tried taking screenshot but it doesn't capture the mouse cursor and also some of the code on screen contains sensitive info i'll have to edit out.  Will try some other methods of getting a screen cap a little later when I have some more free time.

**Comment by Arcanemagus** [comment]
@thehans I think the link I gave above is probably sufficient, no need to worry about getting a screenshot.

**Comment by thehans** [comment]
Here is an animated picture showing two differently sized linter panes.  I can't get screenshots to capture my cursor but i resized it by clicking a seemingly 1px wide border of this pane.  I've cropped out most of the screen for privacy.
![linter-ui-resize](https://cloud.githubusercontent.com/assets/252233/18495353/ebc5927c-79e2-11e6-9219-c8b133d02bf2.gif)

**Comment by thehans** [comment]
@steelbrain Any comment on the above?  If that resize functionality is not part of linter-ui then where would it be?

**Comment by steelbrain** [comment]
@thehans This is the right package to discuss the resize. It's not implemented yet but it'll be eventually implemented

**Comment by thehans** [comment]
You keep saying its not implemented, and I keep saying I can already resize it.  Please explain how I can resize this pane, as shown in screenshot of my previous comment here, if it is not implemented: https://github.com/steelbrain/linter-ui-default/issues/91#issuecomment-246863043

**Comment by steelbrain** [comment]
You are using the currently released version of linter which is v1, this repo and the master of linter is v2. It is unreleased. I am referring to the latest revision and you are referring to the latest version. That's the difference
